import {test} from 'node:test';import assert from 'node:assert/strict';
import {releaseTargetCatalog,releaseOperationMeanings,defineReleaseTargets,planReleaseTargets,formatReleaseTargets} from '../index.mjs';
const passed=target=>Object.fromEntries(releaseTargetCatalog[target].checks.map(x=>[x.id,{status:'passed',reason:`Synthetic fixture verified ${target}:${x.id}`} ]));
test('catalog exposes seven distinct release destinations',()=>{assert.equal(Object.keys(releaseTargetCatalog).length,7);assert.ok(Object.isFrozen(releaseTargetCatalog.web.checks));assert.notDeepEqual(releaseTargetCatalog['github-source'].checks,releaseTargetCatalog['hub-package'].checks)});
test('github-only ignores unselected mobile signing failures',()=>{const p=planReleaseTargets(['github-source'],{'github-source':passed('github-source'),'ios-app-store':{signing:{status:'absent',reason:'No iOS signature in fixture'}}});assert.equal(p.ready,true);assert.equal(p.targets.length,1);assert.deepEqual(p.blockers,[]);assert.equal(p.executable,false);assert.equal(p.authority,'preparation-only')});
test('source synchronization does not satisfy package or backend checks',()=>{const p=planReleaseTargets(['github-source','hub-package','backend'],{'github-source':passed('github-source')});assert.equal(p.targets[0].ready,true);assert.equal(p.targets[1].ready,false);assert.equal(p.targets[2].ready,false);assert.ok(p.blockers.every(x=>x.target!=='github-source'))});
test('absent failed unimplemented and unobserved retain distinct exact reasons',()=>{const reasons={artifact:{status:'absent',reason:'Bundle file absent in synthetic fixture'},'native-runtime':{status:'unimplemented',reason:'iOS renderer has no adapter'},'device-tests':{status:'not-observed',reason:'No iOS device run performed'},signing:{status:'failed',reason:'Fixture signature digest mismatched'}};const p=planReleaseTargets(['ios-app-store'],{'ios-app-store':reasons});for(const [id,e] of Object.entries(reasons)){const actual=p.blockers.find(x=>x.id===id);assert.equal(actual.status,e.status);assert.equal(actual.reason,e.reason)}});
test('default means not observed rather than absent credentials',()=>{const p=planReleaseTargets(['backend']);assert.ok(p.blockers.every(x=>x.status==='not-observed'));assert.match(p.blockers.find(x=>x.id==='secret-refs').reason,/No observation supplied/)});
test('all target evidence can pass synthetic dryrun without execution',()=>{const selected=Object.keys(releaseTargetCatalog),p=planReleaseTargets(selected,Object.fromEntries(selected.map(x=>[x,passed(x)])));assert.equal(p.ready,true);assert.equal(p.executable,false);assert.match(p.trust,/no live observation/)});
test('invalid targets duplicate targets malformed statuses and unknown checks rejected',()=>{for(const x of [[],['dns'],['web','web']])assert.throws(()=>defineReleaseTargets(x));assert.throws(()=>planReleaseTargets(['web'],{web:{artifact:{status:'done',reason:'unsupported'}}}));assert.throws(()=>planReleaseTargets(['web'],{web:{artifact:{status:'passed',reason:''}}}));assert.throws(()=>planReleaseTargets(['web'],{web:{typo:{status:'passed',reason:'typo'}}}))});
test('format reports exact blockers and plan is immutable',()=>{const p=planReleaseTargets(['android-play'],{'android-play':{signing:{status:'absent',reason:'Fixture contains no Android signature'}}});assert.match(formatReleaseTargets(p),/absent signing: Fixture contains no Android signature/);assert.ok(Object.isFrozen(p.targets[0].checks[0]));assert.throws(()=>p.selected.push('web'))});

test('push build release publish deploy and submit remain separate concepts',()=>{assert.equal(Object.keys(releaseOperationMeanings).length,6);assert.deepEqual(releaseTargetCatalog['github-source'].operations,['push']);assert.ok(releaseTargetCatalog['hub-package'].operations.includes('publish'));assert.ok(releaseTargetCatalog.backend.operations.includes('deploy'));assert.ok(releaseTargetCatalog['ios-app-store'].operations.includes('submit'));assert.ok(!releaseTargetCatalog['github-source'].operations.includes('submit'))});
