import type {Json} from './index.js';
import type {RealtimeSocketFactory} from './live.js';
export class GPTLiveError extends Error {code:string;constructor(code:string,message:string)}
export type GPTLiveHistoryMessage = {type:'message';role:'developer'|'user';content:[{type:'input_text';text:string}]}|{type:'message';role:'assistant';content:[{type:'text'|'output_text';text:string}]};
export interface GPTLiveSessionConfig {model:string;instructions?:string;audio:{format:{type:'audio/pcm';rate:24000};output?:{voice?:string}};delegation:{type:'client'};store?:boolean;input?:GPTLiveHistoryMessage[]}
export interface GPTLiveClientOptions {apiKey:string;socketFactory?:RealtimeSocketFactory;timeoutMs?:number;closeTimeoutMs?:number}
export type GPTLiveEvent = {type:'session.started'|'session.updated';session:{id:string;[key:string]:Json}}|{type:'session.delegation.created';offset_ms:number;delegation:{id:string;type:'delegation';target:'client'}}|{type:'session.input_transcript.delta'|'session.output_transcript.delta';delta:string;start_ms:number;end_ms:number}|{type:'session.output_audio.delta';delta:string}|{type:'session.commentary.appended'|'session.thinking.appended'|'session.instructions.appended'|'session.input_audio.muted'|'session.input_audio.unmuted';client_event_id:string;start_ms?:number;end_ms?:number}|{type:'session.usage.updated';usage:{seconds:number};context_window?:{usage_ratio:number}}|GPTLiveClosedEvent|{type:'error';error:{type?:string;code?:string;message:string;client_event_id?:string}}|{type:string;[key:string]:Json|undefined};
export interface GPTLiveClosedEvent {type:'session.closed';reason:string;usage:{seconds:number};session?:{id:string;[key:string]:Json}}
export const gptLiveCapabilities:Readonly<{protocol:'gpt-live';delegation:'client';transport:'server-websocket';continuousAudio:true;audioCommit:false;providerCancel:false;webRTC:false;sideband:false;liveVerified:false}>;
export class GPTLiveClient {constructor(options:GPTLiveClientOptions);connect(options:{session:GPTLiveSessionConfig;signal?:AbortSignal}):Promise<GPTLiveSession>;reconnect(previous:GPTLiveSession,options:{session:GPTLiveSessionConfig;signal?:AbortSignal}):Promise<GPTLiveSession>}
export class GPTLiveSession {private constructor();readonly state:'connecting'|'starting'|'ready'|'closing'|'closed'|'failed';readonly sessionId?:string;readonly finalized:boolean;readonly usageSeconds:number;ready():Promise<GPTLiveSession>;appendAudio(audio:string):void;appendCommentary(delegationId:string|null,content:string,options?:{eventId?:string}):string;appendThinking(delegationId:string|null,content:string,options?:{eventId?:string}):string;appendInstructions(delegationId:string|null,content:string,options?:{eventId?:string}):string;muteInput(options?:{eventId?:string}):string;unmuteInput(options?:{eventId?:string}):string;events():AsyncGenerator<GPTLiveEvent>;close():Promise<GPTLiveClosedEvent>;abort():void}
