export type Json = null | boolean | number | string | Json[] | { [key: string]: Json };
export type JsonObject = { [key: string]: Json };
export interface RequestOptions { signal?: AbortSignal }
export interface ClientOptions { apiKey: string; fetch?: typeof globalThis.fetch; baseURL?: string; allowInsecureLocalhost?: boolean }
export class ProviderError extends Error { provider: string; code: string; status: number; requestId?: string | null; retryAfter?: string | null; constructor(provider: string, code: string, message: string, metadata?: {status?:number; requestId?:string|null; retryAfter?:string|null}); }
export function parseSSE(body: ReadableStream<Uint8Array>, options?: RequestOptions & { maxFrameBytes?: number }): AsyncGenerator<{ event?: string; data: string }>;
export interface FunctionTool { type: 'function'; function: { name: string; description?: string; parameters: JsonObject } }
export interface ChatMessage { role: 'system' | 'user' | 'assistant' | 'tool'; content: string | {type:'text'; text:string}[]; tool_call_id?: string; tool_calls?: { id:string; type:'function'; function:{name:string; arguments:string} }[] }
export interface OpenRouterRequest { model: string; messages: ChatMessage[]; tools?: FunctionTool[]; tool_choice?: 'auto'|'none'|'required'|{type:'function';function:{name:string}}; temperature?: number; max_tokens?:number; models?:string[]; route?:'fallback'; provider?:{order?:string[];allow_fallbacks?:boolean;require_parameters?:boolean;only?:string[];ignore?:string[]}; response_format?: {type:'json_object'} | {type:'json_schema';json_schema:{name:string;strict?:boolean;schema:JsonObject}}; reasoning?:{effort?:'low'|'medium'|'high';max_tokens?:number;exclude?:boolean}; }
export interface ChatUsage {prompt_tokens:number;completion_tokens:number;total_tokens:number;cost?:number}
export interface ChatCompletion {id:string;object:'chat.completion';model:string;choices:{index:number;message:ChatMessage;finish_reason:string|null}[];usage?:ChatUsage}
export interface ChatChunk {id:string;object:'chat.completion.chunk';model:string;choices:{index:number;delta:Partial<ChatMessage>;finish_reason:string|null}[];usage?:ChatUsage}
export class OpenRouterClient {constructor(options:ClientOptions & {referer?:string;title?:string});complete(request:OpenRouterRequest,options?:RequestOptions):Promise<ChatCompletion>;stream(request:OpenRouterRequest,options?:RequestOptions):AsyncGenerator<ChatChunk>}
export type ResponseInput = {role:'user'|'assistant'|'system'|'developer';content:string} | {type:'function_call_output';call_id:string;output:string};
export interface OpenAIRequest {model:string;input:string|ResponseInput[];instructions?:string;previous_response_id?:string;store?:boolean;max_output_tokens?:number;tools?:{type:'function';name:string;description?:string;parameters:JsonObject;strict?:boolean}[];reasoning?:{effort?:'none'|'minimal'|'low'|'medium'|'high'|'xhigh';summary?:'auto'|'concise'|'detailed'};text?:{format:{type:'json_schema';name:string;strict?:boolean;schema:JsonObject}}}
export type ResponseOutput = {type:'message';id:string;role:'assistant';content:({type:'output_text';text:string;annotations:Json[]}|{type:'refusal';refusal:string})[]} | {type:'function_call';id:string;call_id:string;name:string;arguments:string};
export interface OpenAIResponse {id:string;status:'completed'|'failed'|'incomplete'|'in_progress'|'queued';output:ResponseOutput[];usage?:{input_tokens:number;output_tokens:number;total_tokens:number};error?:{code:string;message:string}|null}
export type OpenAIEvent = {type:'response.output_text.delta';delta:string;item_id:string;output_index:number;content_index:number;sequence_number:number} | {type:'response.completed';response:OpenAIResponse;sequence_number:number} | {type:'response.created'|'response.in_progress';response:OpenAIResponse;sequence_number:number} | {type:'response.function_call_arguments.delta';delta:string;item_id:string;output_index:number;sequence_number:number} | {type:string;[key:string]:Json};
export class OpenAIClient {constructor(options:ClientOptions);createResponse(request:OpenAIRequest,options?:RequestOptions):Promise<OpenAIResponse>;streamResponse(request:OpenAIRequest,options?:RequestOptions):AsyncGenerator<OpenAIEvent>}
export type AnthropicContent = {type:'thinking';thinking:string;signature:string} | {type:'redacted_thinking';data:string} | {type:'text';text:string} | {type:'tool_use';id:string;name:string;input:JsonObject} | {type:'tool_result';tool_use_id:string;content:string;is_error?:boolean};
export interface AnthropicRequest {model:string;max_tokens:number;messages:{role:'user'|'assistant';content:string|AnthropicContent[]}[];system?:string;tools?:{name:string;description?:string;input_schema:JsonObject}[];tool_choice?:{type:'auto'|'any'|'none'}|{type:'tool';name:string};thinking?:{type:'enabled';budget_tokens:number}|{type:'disabled'};temperature?:number}
export interface AnthropicMessage {id:string;type:'message';role:'assistant';model:string;content:AnthropicContent[];stop_reason:string|null;usage:{input_tokens:number;output_tokens:number;cache_creation_input_tokens?:number;cache_read_input_tokens?:number}}
export type AnthropicEvent = {type:'message_start';message:AnthropicMessage} | {type:'content_block_delta';index:number;delta:{type:'text_delta';text:string}|{type:'input_json_delta';partial_json:string}|{type:'thinking_delta';thinking:string}|{type:'signature_delta';signature:string}} | {type:'message_stop'} | {type:string;[key:string]:Json};
export class AnthropicClient {constructor(options:ClientOptions);createMessage(request:AnthropicRequest,options?:RequestOptions):Promise<AnthropicMessage>;streamMessage(request:AnthropicRequest,options?:RequestOptions):AsyncGenerator<AnthropicEvent>}
export interface SpeechRequest {text:string;model_id?:string;language_code?:string;voice_settings?:{stability?:number;similarity_boost?:number;style?:number;use_speaker_boost?:boolean;speed?:number}}
export interface ScribeV2Options {model_id?:'scribe_v2';language_code?:string|null;tag_audio_events?:boolean;num_speakers?:number|null;timestamps_granularity?:'none'|'word'|'character';diarize?:boolean;file_format?:'other'|'pcm_s16le_16';temperature?:number|null;seed?:number|null;enable_logging?:boolean}
export interface TranscriptionRequest extends ScribeV2Options {file:Blob|Uint8Array;filename?:string;mimeType?:string}
export interface TranscriptionCharacter {text:string;start?:number|null;end?:number|null}
export interface TranscriptionWord {text:string;type:'word'|'spacing'|'audio_event';start?:number|null;end?:number|null;logprob:number;speaker_id?:string|null;characters?:TranscriptionCharacter[];channel_index?:number|null}
export interface SpeechToTextResult {text:string;language_code:string;language_probability:number;words:TranscriptionWord[];transcription_id?:string|null;audio_duration_secs?:number|null;channel_index?:number|null}
export class ElevenLabsClient {constructor(options:ClientOptions);speech(voiceId:string,request:SpeechRequest,options?:RequestOptions & {outputFormat?:string}):Promise<{audio:Uint8Array;contentType:string|null;requestId:string|null}>;transcribe(request:TranscriptionRequest,options?:RequestOptions & {maxFileBytes?:number}):Promise<SpeechToTextResult>}
export const transcriptionCapabilities:Readonly<{model:'scribe_v2';batchFileUpload:true;singleChannel:true;wordTimestamps:true;characterTimestamps:true;diarization:true;maxFileBytes:number;sourceURL:false;webhooks:false;realtime:false;entityDetection:false;transcriptEditing:false;paidEndToEndVerified:false}>;
export const capabilities: Readonly<{openrouter:readonly string[];openai:readonly string[];anthropic:readonly string[];elevenlabs:readonly string[];claudeCli:readonly string[]}>;
export interface ClaudeRequest {prompt:string;resume?:string;allowedTools?:string[]}
export interface ClaudeEvent {type:string;result?:string;session_id?:string;is_error?:boolean;[key:string]:Json|undefined}
export class ClaudeCliAdapter {constructor(options?:{executable?:string;spawn?:typeof import('node:child_process').spawn;cwd?:string;allowExecution?:boolean;terminationGraceMs?:number});plan(request:ClaudeRequest):{executable:string;args:string[];cwd?:string;authentication:string};run(request:ClaudeRequest,options?:RequestOptions):AsyncGenerator<ClaudeEvent>}
export type MockAgentEvent = {type:'text_delta';text:string}|{type:'result';text:string;sessionId:string};
export class MockAgent {run(request:{prompt:string},options?:RequestOptions):AsyncGenerator<MockAgentEvent>}
