import type { Json, JsonObject } from './index.js';
export class RealtimeError extends Error { code:string;constructor(code:string,message:string) }
export interface RealtimeSocket {readyState?:number;on(event:string,handler:(...args:unknown[])=>void):unknown;off(event:string,handler:(...args:unknown[])=>void):unknown;send(data:string):void;close():void}
export type RealtimeSocketFactory = (url:string,options:{headers:{Authorization:string};timeoutMs:number})=>RealtimeSocket|Promise<RealtimeSocket>;
export function defaultSocketFactory(url:string,options:{headers:{Authorization:string};timeoutMs:number}):Promise<RealtimeSocket>;
export interface RealtimeSessionConfig {type?:'realtime';model?:string;instructions?:string;output_modalities?:('audio'|'text')[];audio?:{input?:{format?:{type:'audio/pcm';rate:24000}|{type:'audio/pcmu'|'audio/pcma'};transcription?:{model:string;prompt?:string;language?:string;languages?:string[];keywords?:string[];delay?:'minimal'|'low'|'medium'|'high'|'xhigh'};turn_detection?:null|{type:'server_vad';threshold?:number;prefix_padding_ms?:number;silence_duration_ms?:number;create_response?:boolean;interrupt_response?:boolean}|{type:'semantic_vad';eagerness?:'low'|'medium'|'high'|'auto';create_response?:boolean;interrupt_response?:boolean}};output?:{format?:{type:'audio/pcm';rate:24000}|{type:'audio/pcmu'|'audio/pcma'};voice?:string}};tools?:{type:'function';name:string;description?:string;parameters:JsonObject}[];tool_choice?:'auto'|'none'|'required'}
export interface RealtimeResponseConfig {output_modalities?:('audio'|'text')[];instructions?:string;conversation?:'auto'|'none';metadata?:{[key:string]:string}}
export type RealtimeServerEvent = {type:'session.created'|'session.updated';event_id?:string;session:{id:string;[key:string]:Json}}|{type:'response.created'|'response.done';event_id?:string;response:{id:string;status?:'in_progress'|'completed'|'cancelled'|'failed'|'incomplete';[key:string]:Json|undefined}}|{type:'response.output_audio.delta';event_id?:string;response_id:string;delta:string;item_id:string;output_index:number;content_index:number}|{type:'response.output_text.delta'|'response.output_audio_transcript.delta';event_id?:string;response_id:string;delta:string;item_id:string;output_index:number;content_index:number}|{type:'conversation.item.created';event_id?:string;item:{id:string;type?:string;role?:string;status?:string;content:{type:'input_image'}[]}}|{type:'error';event_id?:string;error:{type:string;code?:string;message:string;event_id?:string}}|{type:string;[key:string]:Json|undefined};
export interface RealtimeImageReceipt {eventId:string;itemId:string}
export const liveCapabilities:Readonly<{imageInput:'requires-capable-model';provider:'openai';protocol:'realtime';transport:'server-websocket';operations:readonly string[];deviceCapture:false;automaticReconnect:false;endToEndLiveVerified:false}>;
export class OpenAIRealtimeClient {constructor(options:{apiKey:string;model:string;socketFactory?:RealtimeSocketFactory;timeoutMs?:number;imageInput?:boolean});connect(options?:{signal?:AbortSignal}):Promise<RealtimeSession>;reconnect(previous:RealtimeSession,options?:{signal?:AbortSignal}):Promise<RealtimeSession>}
export class RealtimeSession {private constructor();readonly state:'connecting'|'open'|'ready'|'closed'|'failed';readonly sessionId?:string;readonly capabilities:Readonly<{imageInput:boolean}>;ready():Promise<RealtimeSession>;configure(session:RealtimeSessionConfig):void;appendAudio(audio:string):void;appendImage(dataURI:string,options?:{eventId?:string;itemId?:string}):RealtimeImageReceipt;commitAudio():void;clearAudio():void;createResponse(response?:RealtimeResponseConfig):void;cancelResponse(responseId?:string):void;events():AsyncGenerator<RealtimeServerEvent>;close():void}
