import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,readFile,readdir,rm,symlink,access,realpath} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {execFileSync,spawnSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {defineSource,defineSourceObservation,sourceSteps} from '../src/provenance.js';
import {observeSource} from '../src/repositories.js';
import {planDeployment} from '../src/index.js';
const hash=bytes=>createHash('sha256').update(bytes).digest('hex');
const git=(root,...args)=>execFileSync('git',['--no-optional-locks','-C',root,...args],{encoding:'utf8',env:{...process.env,GIT_OPTIONAL_LOCKS:'0'}}).trim();
async function fixture(t,{same=false,identical=false}={}){
 const root=await realpath(await mkdtemp(join(tmpdir(),'f-provenance-')));t.after(()=>rm(root,{recursive:true,force:true}));
 async function repo(name){const path=join(root,name);await mkdir(path);git(path,'init','--quiet');git(path,'config','user.name','Synthetic Fixture');git(path,'config','user.email','fixture@example.invalid');await writeFile(join(path,'.gitignore'),'dist/\n');await writeFile(join(path,'source.txt'),identical?'shared synthetic implementation\n':name+' synthetic source\n');git(path,'add','.');execFileSync('git',['-C',path,'commit','--quiet','-m','synthetic fixture'],{env:{...process.env,GIT_AUTHOR_DATE:'2020-01-01T00:00:00Z',GIT_COMMITTER_DATE:'2020-01-01T00:00:00Z'}});return path}
 const model=await repo('model'),implementation=same?model:await repo('implementation');const revision=git(implementation,'rev-parse','HEAD'),modelRevision=git(model,'rev-parse','HEAD');
 const bytes='produced synthetic artifact\n';await mkdir(join(implementation,'dist'));await writeFile(join(implementation,'dist/app.js'),bytes);
 const receipt={repositoryId:'implementation',revision,artifactPath:'dist/app.js',sha256:hash(bytes)};await writeFile(join(implementation,'dist/build.json'),JSON.stringify(receipt));
 const source=defineSource({kind:same?'same-repo':'mirror',...(same?{repository:{id:'implementation',revision}}:{model:{id:'model',revision:modelRevision},implementation:{id:'implementation',revision}}),artifacts:[{path:'dist/app.js',receipt:'dist/build.json',sha256:hash(bytes)}]});
 const roots={model,implementation};const definition={name:'synthetic',version:'1.0.0',services:[{id:'app',runtime:'node',artifact:'dist/app.js'}],source};
 async function plan(){const observation=await observeSource(source,roots);return planDeployment(definition,{source:observation,services:{},artifacts:{'dist/app.js':true},availableSecretRefs:[],previous:{stores:[]}})}
 return{root,model,implementation,revision,source,roots,receipt,definition,plan};
}
const blocked=(plan,subject,pattern)=>assert.ok(plan.steps.some(s=>s.status==='blocked'&&s.subject===subject&&pattern.test(s.detail)),JSON.stringify(plan.steps));
test('distinct mirror resolves actual implementation and verifies bytes plus revision-bound receipt',async t=>{const f=await fixture(t),p=await f.plan();assert.equal(p.readyForReview,true);assert.equal(p.executable,false);assert.equal(p.implementation.root,f.implementation);assert.notEqual(p.implementation.root,f.model);assert.match(p.steps.find(s=>s.subject==='implementation-provenance').detail,/semantic equivalence is not certified/);});
test('same-repository binding preserves supported resolution',async t=>{const f=await fixture(t,{same:true}),p=await f.plan();assert.equal(p.readyForReview,true);assert.equal(p.implementation.root,f.model);});
test('mirror accidentally mapped to model is blocked even with identical commit and artifact content',async t=>{const f=await fixture(t,{identical:true});assert.equal(git(f.model,'rev-parse','HEAD'),f.revision);await mkdir(join(f.model,'dist'));await writeFile(join(f.model,'dist/app.js'),'produced synthetic artifact\n');await writeFile(join(f.model,'dist/build.json'),JSON.stringify(f.receipt));f.roots.implementation=f.model;blocked(await f.plan(),'source-binding',/distinct roots/);});
for(const kind of ['missing','non-git','nested-git','dirty','wrong-revision','wrong-origin'])test('actual target check blocks '+kind,async t=>{const f=await fixture(t);if(kind==='missing')delete f.roots.implementation;if(kind==='non-git'){f.roots.implementation=join(f.root,'plain');await mkdir(f.roots.implementation);}if(kind==='nested-git'){await mkdir(join(f.implementation,'nested'));f.roots.implementation=join(f.implementation,'nested');}if(kind==='dirty')await writeFile(join(f.implementation,'source.txt'),'dirty\n');if(kind==='wrong-revision'){await writeFile(join(f.implementation,'source.txt'),'new revision\n');git(f.implementation,'add','source.txt');git(f.implementation,'commit','--quiet','-m','new');}if(kind==='wrong-origin'){f.source=defineSource({...f.source,implementation:{...f.source.implementation,origin:'https://example.invalid/expected.git'}});f.definition.source=f.source;git(f.implementation,'remote','add','origin','https://example.invalid/wrong.git');}const o=await observeSource(f.source,f.roots);const p=planDeployment(f.definition,{source:o,services:{},artifacts:{'dist/app.js':true},availableSecretRefs:[],previous:{stores:[]}});blocked(p,'implementation-repository',/missing|error|not-git|uncommitted|HEAD|origin/);assert.equal(p.readyForReview,false);});
for(const kind of ['missing-artifact','wrong-bytes','missing-receipt','bad-json','stale-revision','wrong-repository','wrong-path','wrong-hash'])test('artifact provenance blocks '+kind,async t=>{const f=await fixture(t),artifact=join(f.implementation,'dist/app.js'),receiptPath=join(f.implementation,'dist/build.json');if(kind==='missing-artifact')await rm(artifact);if(kind==='wrong-bytes')await writeFile(artifact,'unrelated output');if(kind==='missing-receipt')await rm(receiptPath);if(kind==='bad-json')await writeFile(receiptPath,'{');const changes={'stale-revision':{revision:'a'.repeat(40)},'wrong-repository':{repositoryId:'model'},'wrong-path':{artifactPath:'dist/other.js'},'wrong-hash':{sha256:'b'.repeat(64)}};if(changes[kind])await writeFile(receiptPath,JSON.stringify({...f.receipt,...changes[kind]}));blocked(await f.plan(),'artifact:dist/app.js',/missing|SHA-256|invalid|stale|mismatches/);});
for(const target of ['artifact','receipt'])test(target+' symlink escape cannot be certified',async t=>{const f=await fixture(t);const name=target==='artifact'?'app.js':'build.json',path=join(f.implementation,'dist',name),outside=join(f.root,'outside-'+name);await writeFile(outside,await readFile(path));await rm(path);await symlink(outside,path);blocked(await f.plan(),'artifact:dist/app.js',/unsafe/);});
test('bound oversize artifact read returns failed evidence',async t=>{const f=await fixture(t),o=await observeSource(f.source,f.roots,{maxArtifactBytes:1});assert.equal(o.artifacts['dist/app.js'].status,'error');});
test('model revision and dirty model failures block otherwise correct target provenance',async t=>{const f=await fixture(t);await writeFile(join(f.model,'source.txt'),'modified model');const o=await observeSource(f.source,f.roots);blocked(planDeployment(f.definition,{source:o,services:{},artifacts:{'dist/app.js':true},previous:{stores:[]}}),'model-repository',/uncommitted/);});
test('malformed bindings and unsafe paths reject before host observation',async t=>{const f=await fixture(t);for(const path of ['../app.js','/tmp/app.js','dist//app.js','dist/.git/config','dist\\app.js','dist/./app.js'])assert.throws(()=>defineSource({...f.source,artifacts:[{...f.source.artifacts[0],path}]}),/Artifact pin/);assert.throws(()=>defineSource({...f.source,implementation:{id:'model',revision:f.revision}}),/distinct/);assert.throws(()=>defineSource({...f.source,implementation:{id:'implementation',revision:'HEAD'}}),/revision/);assert.throws(()=>defineSource({...f.source,implementation:{id:'implementation',revision:f.revision,origin:'https://user:password@example.invalid/repo'}}),/credential-free/);await assert.rejects(observeSource(f.source,{implementation:42}),/roots/);await assert.rejects(observeSource(f.source,f.roots,{maxArtifactBytes:0}),/bound/);assert.throws(()=>defineSourceObservation({}),/observation/);});
test('source observations cannot be silently omitted despite true legacy artifact flags',async t=>{const f=await fixture(t);const p=planDeployment(f.definition,{services:{},artifacts:{'dist/app.js':true},previous:{stores:[]}});assert.equal(p.readyForReview,false);assert.ok(p.steps.some(s=>s.status==='unverified'&&s.subject==='implementation-repository'));assert.throws(()=>planDeployment({...f.definition,services:[{id:'app',runtime:'node',artifact:'dist/unpinned.js'}]}),/must be pinned/);});
test('read-only observation leaves HEAD/status/index, source and artifact bytes unchanged',async t=>{const f=await fixture(t),paths=['source.txt','.git/index','dist/app.js','dist/build.json'];const before=await Promise.all(paths.map(p=>readFile(join(f.implementation,p))));const status=git(f.implementation,'status','--porcelain=v1','--untracked-files=all'),head=git(f.implementation,'rev-parse','HEAD'),files=await readdir(join(f.implementation,'.git'));await f.plan();assert.equal(git(f.implementation,'rev-parse','HEAD'),head);assert.equal(git(f.implementation,'status','--porcelain=v1','--untracked-files=all'),status);assert.deepEqual(await readdir(join(f.implementation,'.git')),files);for(let i=0;i<paths.length;i++)assert.deepEqual(await readFile(join(f.implementation,paths[i])),before[i]);});
test('CLI explicit roots replace stale snapshot evidence and artifact booleans with actual target evidence',async t=>{const f=await fixture(t);const binDir=fileURLToPath(new URL('../bin/',import.meta.url));let cli=join(binDir,'near-function.js');try{await access(cli)}catch{cli=join(binDir,'near-function.js')}const definition=join(f.root,'definition.json'),snapshot=join(f.root,'snapshot.json'),roots=join(f.root,'roots.json');await writeFile(definition,JSON.stringify(f.definition));await writeFile(snapshot,JSON.stringify({services:{},artifacts:{'dist/app.js':false},availableSecretRefs:[],previous:{stores:[]}}));await writeFile(roots,JSON.stringify(f.roots));const args=[cli,'dryrun',definition,snapshot,'--repository-roots',roots];const run=()=>spawnSync(process.execPath,args,{encoding:'utf8'});let result=run();assert.equal(result.status,0,result.stderr+result.stdout);assert.match(result.stdout,/Ready for review: yes/);assert.match(result.stdout,/Implementation: implementation@/);await rm(join(f.implementation,'dist/app.js'));await writeFile(snapshot,JSON.stringify({services:{},artifacts:{'dist/app.js':true},previous:{stores:[]}}));result=run();assert.equal(result.status,1,result.stderr+result.stdout);assert.match(result.stdout,/artifact:dist\/app.js: implementation artifact missing/);assert.match(result.stdout,/Ready for review: no/);});
test('legal artifact names that overlap Object prototype remain explicit own evidence keys',async t=>{const f=await fixture(t);const path='__proto__',receipt='dist/prototype-build.json';await writeFile(join(f.implementation,path),'prototype-name artifact');await writeFile(join(f.implementation,'.gitignore'),'dist/\n__proto__\n');git(f.implementation,'add','.gitignore');git(f.implementation,'commit','--quiet','-m','ignore produced prototype-name artifact');const revision=git(f.implementation,'rev-parse','HEAD'),sha256=hash('prototype-name artifact');await writeFile(join(f.implementation,receipt),JSON.stringify({repositoryId:'implementation',revision,artifactPath:path,sha256}));const source=defineSource({...f.source,implementation:{id:'implementation',revision},artifacts:[{path,receipt,sha256}]});const observation=await observeSource(source,f.roots);assert.equal(Object.hasOwn(observation.artifacts,path),true);assert.equal(observation.artifacts[path].status,'verified');assert.equal(sourceSteps(source,observation)[0].status,'current');});
