import test from 'node:test';
import assert from 'node:assert/strict';
import {EventEmitter} from 'node:events';
import {OpenAIRealtimeClient} from '../src/live.mjs';
const png='data:image/png;base64,'+btoa('\x89PNG\r\n\x1a\nfixture');
class Socket extends EventEmitter{readyState=1;sent=[];closed=false;send(wire){this.sent.push(JSON.parse(wire))}close(){this.closed=true}frame(value){this.emit('message',JSON.stringify(value))}}
async function ready(imageInput=true){const socket=new Socket(),client=new OpenAIRealtimeClient({apiKey:'offline-fixture',model:'fixture',imageInput,socketFactory:()=>{setImmediate(()=>socket.frame({type:'session.created',session:{id:'fixture'}}));return socket}});return {socket,session:await client.connect()}}
test('Realtime image lane sends documented bounded input only when model capability enabled',async()=>{const {socket,session}=await ready();const receipt=session.appendImage(png,{eventId:'camera-event',itemId:'camera-item'});assert.deepEqual(receipt,{eventId:'camera-event',itemId:'camera-item'});assert.deepEqual(socket.sent[0],{type:'conversation.item.create',event_id:'camera-event',item:{id:'camera-item',type:'message',role:'user',content:[{type:'input_image',image_url:png}]}});assert.throws(()=>session.appendImage(png,{eventId:'camera-event',itemId:'new'}),e=>e.code==='duplicate_image_id');const maxFrame='data:image/png;base64,'+btoa('\x89PNG\r\n\x1a\n'+'x'.repeat(262136));session.appendImage(maxFrame);session.close();const unsupported=await ready(false);assert.throws(()=>unsupported.session.appendImage(png),e=>e.code==='unsupported_image_input');unsupported.session.close()});
test('Realtime image acknowledgement retains metadata rather than provider image echo',async()=>{const {socket,session}=await ready();session.appendImage(png,{eventId:'camera-event',itemId:'camera-item'});socket.frame({type:'conversation.item.created',item:{id:'camera-item',type:'message',role:'user',content:[{type:'input_image',image_url:png}]}});const iterator=session.events();assert.equal((await iterator.next()).value.type,'session.created');const ack=(await iterator.next()).value;assert.equal(ack.item.id,'camera-item');assert.ok(!JSON.stringify(ack).includes('base64'));await iterator.return();session.close()});
test('Realtime image lane rejects remote URLs, malformed image bytes and excessive size',async()=>{const {session}=await ready();for(const data of ['https://example.com/private.png','data:image/png;base64,AA==','data:image/gif;base64,R0lGODlh',png+'='.repeat(400000)])assert.throws(()=>session.appendImage(data));session.close()});
