import {test} from 'node:test';
import assert from 'node:assert/strict';
import {EventEmitter} from 'node:events';
import {GPTLiveClient,GPTLiveError,gptLiveCapabilities} from '../src/gpt-live.mjs';
const config={model:'fixture-live',audio:{format:{type:'audio/pcm',rate:24000},output:{voice:'fixture'}},delegation:{type:'client'},store:false};
class Socket extends EventEmitter {readyState=0;sent=[];closed=false;send(frame){this.sent.push(JSON.parse(frame));}close(){this.closed=true;this.readyState=3;this.emit('close',1000);}open(){this.readyState=1;this.emit('open');}frame(event){this.emit('message',typeof event==='string'?event:JSON.stringify(event));}}
async function ready(options={}){const socket=new Socket();const client=new GPTLiveClient({apiKey:'fixture-private',socketFactory:(url,opts)=>{options.inspect?.(url,opts);setImmediate(()=>{socket.open();socket.frame({type:'session.started',session:{id:'s1'}});});return socket;},closeTimeoutMs:5,...options.client});const session=await client.connect({session:config,signal:options.signal});return{socket,client,session};}
const collect=async iterator=>{const events=[];for await(const event of iterator)events.push(event);return events;};
const delegate=(socket,id='d1')=>socket.frame({type:'session.delegation.created',offset_ms:10,delegation:{id,type:'delegation',target:'client'}});
test('GPT-Live uses distinct no-query endpoint and session.start first, key stays private',async()=>{const f=await ready({inspect:(url,o)=>{assert.equal(url,'wss://api.openai.com/v1/live/sessions');assert.equal(o.headers.Authorization,'Bearer fixture-private');}});assert.deepEqual(f.socket.sent[0],{type:'session.start',event_id:'start-1',session:config});assert.equal(f.session.state,'ready');assert.equal(f.session.sessionId,'s1');assert.equal(JSON.stringify(f.client),'{}');assert.equal(JSON.stringify(f.session),'{}');assert.equal(gptLiveCapabilities.audioCommit,false);f.session.abort();});
test('session.start configuration is snapshotted before asynchronous socket loading',async()=>{let resolve;const socket=new Socket();const original=structuredClone(config);const client=new GPTLiveClient({apiKey:'fixture',socketFactory:()=>new Promise(r=>resolve=r)});const connecting=client.connect({session:original});original.instructions='mutated after connect';resolve(socket);await new Promise(r=>setImmediate(r));socket.open();socket.frame({type:'session.started',session:{id:'s'}});const session=await connecting;assert.equal(socket.sent[0].session.instructions,undefined);session.abort();});
test('native continuous audio validates complete PCM samples and carries no Realtime commit',async()=>{const f=await ready();f.session.appendAudio('AQIDBA==');assert.deepEqual(f.socket.sent[1],{type:'session.input_audio.append',audio:'AQIDBA=='});assert.throws(()=>f.session.appendAudio('AQ=='),/16-bit/);assert.equal(f.session.commitAudio,undefined);assert.equal(f.session.cancelResponse,undefined);f.session.abort();});
test('client delegation metadata and transcript fragments are preserved; results use matching ID',async()=>{const f=await ready();f.socket.frame({type:'session.input_transcript.delta',delta:'Please check',start_ms:0,end_ms:50});delegate(f.socket);const id=f.session.appendCommentary('d1','Verified fixture result');assert.deepEqual(f.socket.sent[1],{type:'session.commentary.append',event_id:id,delegation_id:'d1',content:'Verified fixture result'});f.socket.frame({type:'session.commentary.appended',client_event_id:id,start_ms:51,end_ms:60});assert.throws(()=>f.session.appendThinking('foreign','x'),e=>e.code==='unknown_delegation');f.session.abort();const iter=f.session.events();assert.equal((await iter.next()).value.type,'session.started');assert.equal((await iter.next()).value.delta,'Please check');assert.equal((await iter.next()).value.delegation.id,'d1');await iter.return();});
test('session-wide append, mute/unmute and acknowledgements use distinct native commands',async()=>{const f=await ready();const thinking=f.session.appendThinking(null,'Trusted factual context');const instructions=f.session.appendInstructions(null,'Wait for confirmation');const mute=f.session.muteInput();const unmute=f.session.unmuteInput();assert.deepEqual(f.socket.sent.slice(1).map(e=>e.type),['session.thinking.append','session.instructions.append','session.input_audio.mute','session.input_audio.unmute']);for(const[type,id]of [['session.thinking.appended',thinking],['session.instructions.appended',instructions],['session.input_audio.muted',mute],['session.input_audio.unmuted',unmute]])f.socket.frame({type,client_event_id:id});assert.equal(f.session.state,'ready');f.session.abort();});
test('append acknowledgment gaps and duplicate pending commands fail safely',async()=>{const f=await ready();f.session.appendCommentary(null,'x',{eventId:'e1'});assert.throws(()=>f.session.appendThinking(null,'x',{eventId:'e1'}),e=>e.code==='duplicate_command');f.socket.frame({type:'session.thinking.appended',client_event_id:'e1'});await assert.rejects(collect(f.session.events()),e=>e.code==='ack_gap');});
test('graceful close waits for final event, keeps events flowing and uses cumulative usage',async()=>{const f=await ready();f.socket.frame({type:'session.usage.updated',usage:{seconds:2}});f.socket.frame({type:'session.usage.updated',usage:{seconds:3}});const closing=f.session.close();assert.equal(f.session.state,'closing');assert.equal(f.socket.closed,false);assert.throws(()=>f.session.appendAudio('AQIDBA=='),e=>e.code==='not_ready');const final={type:'session.closed',reason:'close_requested',usage:{seconds:4},session:{id:'s1'}};f.socket.frame(final);assert.deepEqual(await closing,final);assert.equal(f.session.finalized,true);assert.equal(f.session.usageSeconds,4);assert.equal(f.socket.closed,true);assert.equal((await collect(f.session.events())).at(-1).type,'session.closed');});
test('graceful close timeout and transport disconnect retain unconfirmed usage status',async()=>{const f=await ready();await assert.rejects(f.session.close(),e=>e.code==='finalization_timeout');assert.equal(f.session.finalized,false);const lost=await ready();lost.socket.frame({type:'session.usage.updated',usage:{seconds:2}});lost.socket.emit('close',1006);await assert.rejects(collect(lost.session.events()),e=>e.code==='finalization_unconfirmed');assert.equal(lost.session.usageSeconds,2);assert.equal(lost.session.finalized,false);});
test('initial provider error, socket error, malformed events and usage regression reject',async()=>{const socket=new Socket();const client=new GPTLiveClient({apiKey:'fixture',socketFactory:()=>{setImmediate(()=>{socket.open();socket.frame({type:'error',error:{message:'private'}});});return socket;}});await assert.rejects(client.connect({session:config}),e=>e.code==='provider_error'&&!e.message.includes('private'));for(const trigger of [s=>s.emit('error',Error('private')),s=>s.frame('invalid'),s=>s.frame({type:'session.updated',session:{id:'other'}}),s=>{s.frame({type:'session.usage.updated',usage:{seconds:2}});s.frame({type:'session.usage.updated',usage:{seconds:1}});}]){const f=await ready();trigger(f.socket);await assert.rejects(collect(f.session.events()),GPTLiveError);}});
test('aborted connect never creates a socket; active abort wakes event consumer',async()=>{const controller=new AbortController();controller.abort();let called=false;await assert.rejects(new GPTLiveClient({apiKey:'fixture',socketFactory:()=>called=true}).connect({session:config,signal:controller.signal}),{name:'AbortError'});assert.equal(called,false);const abort=new AbortController();const f=await ready({signal:abort.signal});const events=f.session.events();await events.next();const pending=events.next();abort.abort();await assert.rejects(pending,{name:'AbortError'});assert.equal(f.socket.closed,true);});
test('unsupported mode/audio fails before dialing instead of pretending provider parity',async()=>{let called=false;const client=new GPTLiveClient({apiKey:'fixture',socketFactory:()=>called=true});for(const invalid of [{...config,delegation:{type:'responses'}},{...config,audio:{format:{type:'audio/pcm',rate:16000}}}])await assert.rejects(client.connect({session:invalid}),GPTLiveError);assert.equal(called,false);});
test('fresh reconnect cannot accept previous delegation IDs or foreign-key sessions',async()=>{const sockets=[];const client=new GPTLiveClient({apiKey:'a',socketFactory:()=>{const socket=new Socket();sockets.push(socket);setImmediate(()=>{socket.open();socket.frame({type:'session.started',session:{id:`s${sockets.length}`}});});return socket;}});const first=await client.connect({session:config});delegate(sockets[0],'old');const second=await client.reconnect(first,{session:config});assert.notEqual(first.sessionId,second.sessionId);assert.throws(()=>second.appendCommentary('old','late'),e=>e.code==='unknown_delegation');assert.equal(sockets[1].sent.length,1);const foreign=await ready();await assert.rejects(client.reconnect(foreign.session,{session:config}),/belong/);second.abort();foreign.session.abort();});
test('bounded pending command/delegation/event queues fail without silent audio loss',async()=>{const commands=await ready();for(let i=0;i<256;i++)commands.session.appendThinking(null,'x');assert.throws(()=>commands.session.appendThinking(null,'x'),e=>e.code==='command_overflow');commands.session.abort();const events=await ready();for(let i=0;i<256;i++)events.socket.frame({type:'session.output_audio.delta',delta:'AQIDBA=='});await assert.rejects(collect(events.session.events()),e=>e.code==='consumer_overflow');const delegations=await ready();for(let i=0;i<129;i++)delegate(delegations.socket,`d${i}`);await assert.rejects(collect(delegations.session.events()),e=>e.code==='delegation_overflow');});

test('native GPT-Live startup history uses one role-specific text part and bounded messages',async()=>{const socket=new Socket();const client=new GPTLiveClient({apiKey:'fixture',socketFactory:()=>{setImmediate(()=>{socket.open();socket.frame({type:'session.started',session:{id:'s'}});});return socket;}});const history=[{type:'message',role:'user',content:[{type:'input_text',text:'fixture'}]},{type:'message',role:'assistant',content:[{type:'output_text',text:'fixture reply'}]}];const session=await client.connect({session:{...config,input:history}});assert.deepEqual(socket.sent[0].session.input,history);session.abort();for(const input of [[{role:'user',content:'shortcut'}],[{type:'message',role:'user',content:[{type:'output_text',text:'wrong'}]}],Array(129).fill(history[0])])await assert.rejects(client.connect({session:{...config,input}}),e=>['history_protocol','history_limit'].includes(e.code));});
test('acknowledged command IDs cannot be reused for stale acknowledgment confusion',async()=>{const f=await ready();f.session.appendThinking(null,'x',{eventId:'fixed'});f.socket.frame({type:'session.thinking.appended',client_event_id:'fixed'});assert.throws(()=>f.session.appendCommentary(null,'later',{eventId:'fixed'}),e=>e.code==='duplicate_command');f.session.abort();});
