import {test} from 'node:test';
import assert from 'node:assert/strict';
import {EventEmitter} from 'node:events';
import {OpenAIRealtimeClient, RealtimeError, liveCapabilities} from '../src/live.mjs';
class Socket extends EventEmitter {readyState=0;sent=[];closed=false;send(frame){this.sent.push(JSON.parse(frame));}close(){this.closed=true;this.readyState=3;this.emit('close',1000);}open(id='sess-fixture'){this.readyState=1;this.emit('open');this.frame({type:'session.created',session:{id}});}frame(event){this.emit('message',typeof event==='string'?event:JSON.stringify(event));}}
async function ready({key='fixture-key',id='sess-fixture',inspect=()=>{},signal}={}) {const socket=new Socket();const client=new OpenAIRealtimeClient({apiKey:key,model:'fixture-realtime',socketFactory:(url,options)=>{inspect(url,options);setImmediate(()=>socket.open(id));return socket;}});const session=await client.connect({signal});return {client,socket,session};}
const collect=async events=>{const out=[];for await(const e of events)out.push(e);return out;};
test('Realtime server handshake uses Authorization privately and waits for session.created',async()=>{const {client,session,socket}=await ready({inspect:(url,options)=>{assert.equal(url,'wss://api.openai.com/v1/realtime?model=fixture-realtime');assert.equal(options.headers.Authorization,'Bearer fixture-key');assert.ok(!url.includes('fixture-key'));}});assert.equal(session.state,'ready');assert.equal(session.sessionId,'sess-fixture');assert.equal(JSON.stringify(client),'{}');assert.equal(JSON.stringify(session),'{}');assert.equal(liveCapabilities.endToEndLiveVerified,false);session.close();assert.equal(socket.closed,true);});
test('Realtime sends typed configure append commit clear create cancel event shapes',async()=>{const {session,socket}=await ready();session.configure({instructions:'fixture',audio:{input:{format:{type:'audio/pcm',rate:24000},turn_detection:null}}});session.appendAudio('AQID');session.commitAudio();session.clearAudio();session.createResponse({output_modalities:['text']});session.cancelResponse('resp-1');assert.deepEqual(socket.sent.map(e=>e.type),['session.update','input_audio_buffer.append','input_audio_buffer.commit','input_audio_buffer.clear','response.create','response.cancel']);assert.equal(socket.sent[0].session.type,'realtime');assert.deepEqual(socket.sent[5],{type:'response.cancel',response_id:'resp-1'});assert.throws(()=>session.appendAudio('not base64'),/base64/);session.close();assert.throws(()=>session.commitAudio(),e=>e.code==='not_ready');});
test('Realtime delivers response/audio/cancel lifecycle without fabricated model results',async()=>{const {session,socket}=await ready();socket.frame({type:'response.created',response:{id:'resp-1',status:'in_progress'}});socket.frame({type:'response.output_audio.delta',response_id:'resp-1',delta:'AQID'});session.cancelResponse('resp-1');socket.frame({type:'response.done',response:{id:'resp-1',status:'cancelled'}});session.close();assert.deepEqual((await collect(session.events())).map(e=>e.type),['session.created','response.created','response.output_audio.delta','response.done']);});
test('provider error event leaves session available for later response',async()=>{const {session,socket}=await ready();socket.frame({type:'error',error:{type:'invalid_request_error',code:'response_cancel_not_active',message:'fixture'}});assert.equal(session.state,'ready');session.createResponse();session.close();assert.equal((await collect(session.events()))[1].type,'error');});
test('malformed frame and protocol lifecycle gap terminate with typed error',async()=>{for(const event of ['bad',null,{type:'response.done',response:{id:'missing'}},{type:'response.output_audio.delta',response_id:'missing',delta:'AQID'}]){const {session,socket}=await ready();socket.frame(event===null?'null':event);assert.equal(session.state,'failed');await assert.rejects(collect(session.events()),RealtimeError);assert.equal(socket.closed,true);}});
test('session identity mismatch and duplicate creation are rejected',async()=>{for(const event of [{type:'session.updated',session:{id:'foreign'}},{type:'session.created',session:{id:'foreign'}},{type:'response.created',response:{id:'r'}}]){const {session,socket}=await ready();if(event.type==='response.created')socket.frame(event);socket.frame(event);await assert.rejects(collect(session.events()),e=>['session_mismatch','protocol_gap'].includes(e.code));}});
test('connect factory failures are sanitized and handshake close/error reject',async()=>{await assert.rejects(new OpenAIRealtimeClient({apiKey:'private',model:'fixture',socketFactory:()=>{throw Error('private');}}).connect(),e=>e.code==='connect_error'&&!e.message.includes('private'));for(const trigger of [s=>s.emit('error',Error('private')),s=>s.emit('close',1006),s=>s.frame({type:'response.created',response:{id:'early'}})]){const socket=new Socket();const client=new OpenAIRealtimeClient({apiKey:'fixture',model:'fixture',socketFactory:()=>{setImmediate(()=>trigger(socket));return socket;}});await assert.rejects(client.connect(),RealtimeError);assert.equal(socket.closed,true);}});
test('connect timeout rejects and tears down listeners',async()=>{const socket=new Socket();await assert.rejects(new OpenAIRealtimeClient({apiKey:'fixture',model:'fixture',socketFactory:()=>socket,timeoutMs:5}).connect(),e=>e.code==='connect_timeout');assert.equal(socket.closed,true);assert.equal(socket.listenerCount('message'),0);});
test('aborting before socket creation never dials; aborting ready session wakes consumers',async()=>{const before=new AbortController();before.abort();let called=false;await assert.rejects(new OpenAIRealtimeClient({apiKey:'fixture',model:'fixture',socketFactory:()=>{called=true;}}).connect({signal:before.signal}),{name:'AbortError'});assert.equal(called,false);const abort=new AbortController();const {session,socket}=await ready({signal:abort.signal});const iterator=session.events();await iterator.next();const pending=iterator.next();abort.abort();await assert.rejects(pending,{name:'AbortError'});assert.equal(socket.closed,true);});
test('close while response active fails with continuity gap and reconnect starts a fresh session',async()=>{const sockets=[];const client=new OpenAIRealtimeClient({apiKey:'fixture',model:'fixture',socketFactory:()=>{const s=new Socket();sockets.push(s);setImmediate(()=>s.open(`sess-${sockets.length}`));return s;}});const old=await client.connect();sockets[0].frame({type:'response.created',response:{id:'r'}});sockets[0].emit('close',1006);await assert.rejects(collect(old.events()),e=>e.code==='disconnected');const next=await client.reconnect(old);assert.notEqual(next.sessionId,old.sessionId);assert.deepEqual(sockets[1].sent,[]);assert.equal(sockets[0].listenerCount('message'),0);next.close();});
test('sessions from different keys are isolated without key exports or automatic replay',async()=>{const first=await ready({key:'fixture-one',id:'s1',inspect:(_url,o)=>assert.equal(o.headers.Authorization,'Bearer fixture-one')});const second=await ready({key:'fixture-two',id:'s2',inspect:(_url,o)=>assert.equal(o.headers.Authorization,'Bearer fixture-two')});first.session.configure({instructions:'first'});assert.equal(second.socket.sent.length,0);second.socket.frame({type:'session.updated',session:{id:'s1'}});await assert.rejects(collect(second.session.events()),e=>e.code==='session_mismatch');assert.equal(first.session.state,'ready');assert.ok(!JSON.stringify(first.session).includes('fixture-one'));first.session.close();});
test('bounded event queue fails instead of dropping realtime audio events',async()=>{const {session,socket}=await ready();for(let i=0;i<256;i++)socket.frame({type:'input_audio_buffer.speech_started',event_id:`e${i}`});await assert.rejects(collect(session.events()),e=>e.code==='consumer_overflow');});
test('early event consumer return closes socket; single consumer enforced',async()=>{const {session,socket}=await ready();const first=session.events();await first.next();const second=session.events();await assert.rejects(second.next(),e=>e.code==='consumer_exists');await first.return();assert.equal(socket.closed,true);});

test('foreign-key reconnect is rejected without closing either session',async()=>{const a=await ready({key:'a',id:'s1'});const b=await ready({key:'b',id:'s2'});await assert.rejects(a.client.reconnect(b.session),/belong/);assert.equal(a.session.state,'ready');assert.equal(b.session.state,'ready');a.session.close();b.session.close();});
test('provider error before session initialization fails promptly and late transport errors drain',async()=>{const socket=new Socket();const client=new OpenAIRealtimeClient({apiKey:'fixture',model:'fixture',socketFactory:()=>{setImmediate(()=>socket.frame({type:'error',error:{message:'private'}}));return socket;}});await assert.rejects(client.connect(),e=>e.code==='provider_error'&&!e.message.includes('private'));assert.doesNotThrow(()=>socket.emit('error',Error('late private')));});
