import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,readFileSync,writeFileSync,rmSync} from 'node:fs';import {join,resolve} from 'node:path';import {tmpdir} from 'node:os';import {spawnSync} from 'node:child_process';import {pathToFileURL} from 'node:url';
import {createAsyncNativeHost,installNativeHost,runNativeIO,embedNativeMain} from '../native-host/host.mjs';
const root=resolve(import.meta.dirname,'../../../../..'),temp=mkdtempSync(join(tmpdir(),'near-native-transcription-')),compiler=join(root,'tools/bend/main.ts'),source=join(root,'packages/function/stdlib/ai/bend/transcription.bend');
const compile=(input,out,proof=false)=>{const result=spawnSync('bun',[compiler,input,...(proof?['--check-only']:['-o',out])],{encoding:'utf8',timeout:120000,maxBuffer:4*1024*1024,killSignal:'SIGKILL'});assert.equal(result.status,0,result.stdout+result.stderr)};
compile(source,null,true);compile(source,join(temp,'native.mjs'));const T=(await import(pathToFileURL(join(temp,'native.mjs')))).default;
process.on('exit',()=>rmSync(temp,{recursive:true,force:true}));
const tag=(name,fields={})=>({$:name,...fields});const list=xs=>xs.reduceRight((tail,head)=>tag('Con',{head,tail}),tag('Nil'));const rows=xs=>{const result=[];while(xs.$==='Con'){result.push(xs.head);xs=xs.tail}return result};const kind=x=>x.$.split('.').at(-1);
const req=()=>tag('TranscriptionRequest',{file:tag('AudioFile',{filename:'voice.webm',mime:tag('WebM'),bytes:list([1,0,255])}),language:tag('Some',{value:'en'}),diarize:true,speakers:tag('Some',{value:2}),timestamps:tag('WordTimestamps'),tag_audio_events:true,format:tag('EncodedAudio')});
const result={text:'Hello',language_code:'eng',language_probability:0.98,words:[{text:'Hello',type:'word',start:0,end:0.5,logprob:-0.1,speaker_id:'speaker_0',characters:[{text:'H',start:0,end:0.1}]}],transcription_id:'fixture',audio_duration_secs:1};
test('native typed Scribe request encodes generic multipart plan with untouched upload',()=>{const encoded=T.request(req());assert.equal(encoded.$,'Done');assert.equal(encoded.value.url,'https://api.elevenlabs.io/v1/speech-to-text');assert.equal(T.mime(encoded.value.file.mime),'audio/webm');const fields=Object.fromEntries(rows(encoded.value.fields).map(f=>[f.name,f.value]));assert.deepEqual(fields,{model_id:'scribe_v2',diarize:'true',timestamps_granularity:'word',tag_audio_events:'true',file_format:'other',language_code:'en',num_speakers:'2'});assert.deepEqual(rows(encoded.value.file.bytes),[1,0,255]);let bad=req();bad.file.filename='../secret';assert.equal(T.request(bad).$,'Fail');bad=req();bad.file.bytes=list([999]);assert.equal(T.request(bad).$,'Fail');bad=req();bad.speakers=tag('Some',{value:33});assert.equal(T.request(bad).$,'Fail')});
test('native transcription JSON codec validates provider timings and typed words',()=>{const decoded=T.decode(JSON.stringify(result));assert.equal(decoded.$,'Done');assert.equal(decoded.value.text,'Hello');const word=rows(decoded.value.words)[0];assert.equal(kind(word.kind),'Word');assert.ok(Math.abs(word.logprob+0.1)<0.00001);assert.equal(rows(word.characters)[0].text,'H');for(const value of [{...result,language_probability:2},{...result,words:[{...result.words[0],end:-1}]},{...result,words:[{...result.words[0],type:'unknown'}]},[]])assert.equal(T.decode(JSON.stringify(value)).$,'Fail')});
for(const name of ['transcription','transcription-cancel']){const out=join(temp,name+'.js');compile(join(import.meta.dirname,'fixtures',name+'.bend'),out);writeFileSync(out+'.mjs',embedNativeMain(readFileSync(out,'utf8')))}
const mains={upload:(await import(pathToFileURL(join(temp,'transcription.js.mjs')))).default,cancel:(await import(pathToFileURL(join(temp,'transcription-cancel.js.mjs')))).default};
test('actual compiled native multipart IO owns HTTP guard, decode, cleanup and cancellation',async()=>{
 for(const mode of ['success','http_error','bad_metadata','invalid_json','cancel']){let opened,closed=0,reads=0;const wire=mode==='invalid_json'?'{broken':JSON.stringify(result),chunks=[wire.slice(0,10),wire.slice(10)];const host=createAsyncNativeHost({credentials:new Map([[7,'private-fixture']]),multipart:async request=>{opened=request;return {status:1,data:mode==='http_error'?'401':mode==='bad_metadata'?'0200':'200',resource:{async read(){reads++;return chunks.length?{status:1,data:chunks.shift()}:{status:2,data:''}},async close(){closed++;return {status:1,data:''}}}}}});const remove=installNativeHost(host);try{const main=mode==='cancel'?mains.cancel:mains.upload;const output=await runNativeIO(main(),{dispose:()=>host.dispose()});assert.deepEqual(opened.bytes,[1,0,255]);assert.equal(opened.credential,'private-fixture');assert.equal(closed,1);assert.equal(host.openHandles,0);if(mode==='success'){assert.equal(kind(output.event),'Completed');assert.equal(output.event.transcript.text,'Hello')}else if(mode==='cancel'){assert.equal(kind(output.event),'CancelledEvent')}else{assert.equal(kind(output.event),'FailedEvent');if(mode==='http_error'){assert.equal(output.event.error.status,401);assert.equal(reads,0)}if(mode==='bad_metadata')assert.equal(reads,0)}}finally{remove()}}
});
