import { test } from 'node:test';
import assert from 'node:assert/strict';
import { EventEmitter } from 'node:events';
import { PassThrough } from 'node:stream';
import { OpenRouterClient, OpenAIClient, AnthropicClient, ElevenLabsClient, ClaudeCliAdapter, MockAgent, ProviderError, parseSSE, capabilities } from '../src/index.mjs';
const collect = async iterable => { const items=[]; for await(const item of iterable) items.push(item); return items; };
function response(chunks, headers = {}) { const encoder=new TextEncoder();return new Response(new ReadableStream({start(c){for(const s of chunks)c.enqueue(encoder.encode(s));c.close();}}),{headers}); }
const sse = (...events) => response(events.map(e => `data: ${typeof e==='string'?e:JSON.stringify(e)}\n\n`));
function client(Class, result, inspect = () => {}) { return new Class({apiKey:'fixture-only',fetch:async(url,init)=>{inspect(url,init);return result;}}); }
test('server package has independent immutable capability report',()=>{assert.deepEqual(capabilities.elevenlabs,['speech.create','speech.transcribe']);assert.ok(Object.isFrozen(capabilities.openai));});
test('SSE handles split UTF8, CRLF, comments and multiline data',async()=>{const items=await collect(parseSSE(response([': keepalive\r\nevent: chunk\r\ndata: first\r\n','data: second\r\n\r\n']).body));assert.deepEqual(items,[{event:'chunk',data:'first\nsecond'}]);});
test('SSE rejects truncated and oversized frames',async()=>{await assert.rejects(collect(parseSSE(response(['data: {}']).body)),/Truncated/);await assert.rejects(collect(parseSSE(response(['data: abcdef\n\n']).body,{maxFrameBytes:3})),/size limit/);});
test('OpenRouter keeps routing and tool parameters',async()=>{const request={model:'vendor/model',messages:[{role:'user',content:'hi'}],provider:{only:['fixture']},tools:[{type:'function',function:{name:'echo',parameters:{type:'object'}}}]};const result={id:'r',choices:[]};const c=client(OpenRouterClient,Response.json(result),(url,init)=>{assert.equal(url,'https://openrouter.ai/api/v1/chat/completions');assert.equal(init.headers.authorization,'Bearer fixture-only');assert.deepEqual(JSON.parse(init.body),{...request,stream:false});});assert.deepEqual(await c.complete(request),result);});
test('OpenRouter streams deltas then requires DONE',async()=>{const c=client(OpenRouterClient,sse({choices:[{delta:{content:'a'}}]},'[DONE]'));assert.equal((await collect(c.stream({model:'a/b',messages:[]}))).length,1);await assert.rejects(collect(client(OpenRouterClient,sse({choices:[]})).stream({model:'a/b',messages:[]})),/terminal/);});
test('OpenAI response stream ends on completed and preserves events',async()=>{const result={type:'response.completed',response:{id:'a',output:[]}};const c=client(OpenAIClient,sse({type:'response.output_text.delta',delta:'hello'},result));assert.deepEqual(await collect(c.streamResponse({model:'fixture',input:'hello'})),[{type:'response.output_text.delta',delta:'hello'},result]);});
test('OpenAI failed and incomplete events reject',async()=>{for(const type of ['response.failed','response.incomplete'])await assert.rejects(collect(client(OpenAIClient,sse({type})).streamResponse({model:'fixture',input:'x'})),e=>e.code===type);});
test('Anthropic version, max tokens and tool blocks stay provider specific',async()=>{const req={model:'fixture',max_tokens:32,messages:[{role:'user',content:'x'}],tools:[{name:'echo',input_schema:{type:'object'}}]};const c=client(AnthropicClient,Response.json({id:'a',content:[]}),(url,init)=>{assert.equal(url,'https://api.anthropic.com/v1/messages');assert.equal(init.headers['anthropic-version'],'2023-06-01');assert.deepEqual(JSON.parse(init.body),{...req,stream:false});});await c.createMessage(req);assert.throws(()=>c.streamMessage({...req,max_tokens:0}),/max_tokens/);});
test('Anthropic streaming stops on message_stop',async()=>{const c=client(AnthropicClient,sse({type:'message_start'},{type:'content_block_delta',delta:{type:'text_delta',text:'a'}},{type:'message_stop'}));assert.equal((await collect(c.streamMessage({model:'fixture',max_tokens:10,messages:[]}))).length,3);});
test('provider stream errors and malformed JSON reject',async()=>{for(const data of [{error:{message:'private'}},'invalid'])await assert.rejects(collect(client(OpenRouterClient,sse(data)).stream({model:'fixture',messages:[]})),ProviderError);});
test('HTTP errors preserve retry metadata without echoing private payload',async()=>{const c=client(OpenAIClient,new Response('SECRET REQUEST',{status:429,headers:{'x-request-id':'req-1','retry-after':'2'}}));await assert.rejects(c.createResponse({model:'fixture',input:'private'}),e=>e.status===429&&e.requestId==='req-1'&&e.retryAfter==='2'&&!e.message.includes('SECRET'));});
test('invalid JSON response rejects',async()=>{await assert.rejects(client(OpenAIClient,new Response('bad')).createResponse({model:'fixture',input:'x'}),/Invalid JSON/);});
test('ElevenLabs returns binary audio with encoded voice and format',async()=>{const c=client(ElevenLabsClient,new Response(new Uint8Array([1,2,3]),{headers:{'content-type':'audio/mpeg'}}),(url,init)=>{assert.ok(url.includes('/voice%2Fid?output_format=pcm_16000'));assert.equal(init.headers['xi-api-key'],'fixture-only');});const out=await c.speech('voice/id',{text:'hi'},{outputFormat:'pcm_16000'});assert.deepEqual([...out.audio],[1,2,3]);});
test('aborted call never invokes fetch',async()=>{let called=false;const c=new OpenAIClient({apiKey:'fixture',fetch:async()=>{called=true;}});const abort=new AbortController();abort.abort();await assert.rejects(c.createResponse({model:'fixture',input:'x'},{signal:abort.signal}),{name:'AbortError'});assert.equal(called,false);});
test('SSE cancellation cancels underlying source',async()=>{let cancelled=false;const controller=new AbortController();const body=new ReadableStream({start(c){c.enqueue(new TextEncoder().encode('data: {}\n\n'));},cancel(){cancelled=true;}});const iterator=parseSSE(body,{signal:controller.signal});await iterator.next();controller.abort();await assert.rejects(iterator.next(),{name:'AbortError'});assert.equal(cancelled,true);});
test('early consumer return cancels SSE body',async()=>{let cancelled=false;const body=new ReadableStream({start(c){c.enqueue(new TextEncoder().encode('data: {}\n\n'));},cancel(){cancelled=true;}});for await(const _ of parseSSE(body))break;assert.equal(cancelled,true);});
test('HTTPS guard accepts only opted-in loopback',()=>{assert.throws(()=>new OpenAIClient({apiKey:'x',baseURL:'http://public.test',allowInsecureLocalhost:true}),/localhost/);assert.throws(()=>new OpenAIClient({apiKey:'x',baseURL:'http://localhost:9'}),/HTTPS/);assert.ok(new OpenAIClient({apiKey:'x',baseURL:'http://localhost:9',allowInsecureLocalhost:true}));});
function fakeSpawn(lines, code=0) { return (_file,args,options)=>{assert.equal(options.shell,false);const child=new EventEmitter();child.stdout=new PassThrough();child.stderr=new PassThrough();child.exitCode=null;child.kill=()=>{child.exitCode=143;child.stdout.end();queueMicrotask(()=>child.emit('close',143,'SIGTERM'));};queueMicrotask(()=>{for(const frame of lines)child.stdout.write(typeof frame==='string'?frame+'\n':JSON.stringify(frame)+'\n');child.stdout.end();child.exitCode=code;child.emit('close',code,null);});return child;}; }
test('CLI plan disables tools by default and preserves resume without shell',()=>{const p=new ClaudeCliAdapter().plan({prompt:'literal $(echo nope)',resume:'session-id'});assert.ok(p.args.includes('literal $(echo nope)'));assert.equal(p.args[p.args.indexOf('--tools')+1],'');assert.equal(p.args[p.args.indexOf('--resume')+1],'session-id');});
test('CLI requires explicit execution; never launches real CLI in tests',async()=>{await assert.rejects(collect(new ClaudeCliAdapter().run({prompt:'x'})),e=>e.code==='permission_required');});
test('CLI adapter handles result lifecycle with injected process',async()=>{const adapter=new ClaudeCliAdapter({allowExecution:true,spawn:fakeSpawn([{type:'assistant'},{type:'result',result:'ok'}])});assert.equal((await collect(adapter.run({prompt:'x'}))).length,2);});
test('CLI rejects missing terminal, malformed event and nonzero exit',async()=>{for(const [lines,code] of [[[{type:'assistant'}],0],[['invalid'],0],[[{type:'result'}],1],[[{type:'result',is_error:true}],0]])await assert.rejects(collect(new ClaudeCliAdapter({allowExecution:true,spawn:fakeSpawn(lines,code)}).run({prompt:'x'})));});
test('mock adapter offline text and abort lifecycle',async()=>{const controller=new AbortController();const iter=new MockAgent().run({prompt:'hi'},{signal:controller.signal});assert.equal((await iter.next()).value.text,'Local preview: hi');controller.abort();await assert.rejects(iter.next(),{name:'AbortError'});});
test('SSE frame limit permits many small frames in one transport chunk',async()=>{const events=await collect(parseSSE(response(['data: {}\n\ndata: {}\n\ndata: {}\n\n']).body,{maxFrameBytes:12}));assert.equal(events.length,3);});
test('SSE decoder preserves Unicode split between byte chunks',async()=>{const bytes=new TextEncoder().encode('data: "🌍"\n\n');const body=new ReadableStream({start(c){for(const byte of bytes)c.enqueue(Uint8Array.of(byte));c.close();}});assert.deepEqual(await collect(parseSSE(body)),[{event:undefined,data:'"🌍"'}]);});
test('SSE size counts encoded Unicode bytes and validates its bound',async()=>{await assert.rejects(collect(parseSSE(response(['data: 🌍🌍🌍\n\n']).body,{maxFrameBytes:12})),/size limit/);await assert.rejects(collect(parseSSE(response([]).body,{maxFrameBytes:0})),/maxFrameBytes/);});
test('scalar and array stream events reject with protocol metadata',async()=>{for(const item of [null,1,'"x"',[]])await assert.rejects(collect(client(OpenRouterClient,sse(item===null?'null':item)).stream({model:'fixture',messages:[]})),e=>e instanceof ProviderError&&e.code==='protocol');});
test('scalar JSON responses reject with protocol metadata',async()=>{for(const item of [null,1,[]])await assert.rejects(client(OpenAIClient,Response.json(item)).createResponse({model:'fixture',input:'x'}),e=>e.code==='protocol');});
test('provider requests prohibit redirects and preserve abort during JSON reads',async()=>{const controller=new AbortController();const result=Response.json({id:'x'});result.json=async()=>{controller.abort();throw controller.signal.reason;};const c=client(OpenAIClient,result,(_url,init)=>assert.equal(init.redirect,'error'));await assert.rejects(c.createResponse({model:'fixture',input:'x'},{signal:controller.signal}),{name:'AbortError'});});
test('CLI abort signals the injected process and terminates iteration',async()=>{const controller=new AbortController();let killed=false;const spawn=()=>{const child=new EventEmitter();child.stdout=new PassThrough();child.stderr=new PassThrough();child.exitCode=null;child.kill=()=>{killed=true;child.exitCode=143;child.stdout.end();queueMicrotask(()=>child.emit('close',143,'SIGTERM'));};queueMicrotask(()=>child.stdout.write('{"type":"assistant"}\n'));return child;};const iter=new ClaudeCliAdapter({spawn,allowExecution:true}).run({prompt:'x'},{signal:controller.signal});await iter.next();controller.abort();await assert.rejects(iter.next(),{name:'AbortError'});assert.equal(killed,true);});
test('browser mock export shares the server implementation without Node imports',async()=>{const {MockAgent:BrowserMock}=await import('../src/mock.mjs');assert.equal(BrowserMock,MockAgent);});
function stubbornSpawn(signals,{closeOnTerm=false}={}) { return ()=>{const child=new EventEmitter();child.stdout=new PassThrough();child.stderr=new PassThrough();child.exitCode=null;child.kill=signal=>{signals.push(signal);if(signal==='SIGKILL'||closeOnTerm){child.exitCode=143;child.stdout.end();child.emit('close',null,signal);}return true;};setImmediate(()=>child.stdout.write('{"type":"assistant"}\n'));return child;}; }
test('CLI abort escalates only its child after bounded ignored SIGTERM',async()=>{const signals=[];const abort=new AbortController();const iter=new ClaudeCliAdapter({allowExecution:true,spawn:stubbornSpawn(signals),terminationGraceMs:5}).run({prompt:'x'},{signal:abort.signal});await iter.next();abort.abort();await assert.rejects(iter.next(),{name:'AbortError'});await new Promise(r=>setTimeout(r,15));assert.deepEqual(signals,['SIGTERM','SIGKILL']);});
test('CLI early consumer return also applies bounded child teardown',async()=>{const signals=[];const iter=new ClaudeCliAdapter({allowExecution:true,spawn:stubbornSpawn(signals),terminationGraceMs:5}).run({prompt:'x'});await iter.next();await iter.return();await new Promise(r=>setTimeout(r,15));assert.deepEqual(signals,['SIGTERM','SIGKILL']);});
test('CLI timely child close clears kill watchdog',async()=>{const signals=[];const iter=new ClaudeCliAdapter({allowExecution:true,spawn:stubbornSpawn(signals,{closeOnTerm:true}),terminationGraceMs:5}).run({prompt:'x'});await iter.next();await iter.return();await new Promise(r=>setTimeout(r,15));assert.deepEqual(signals,['SIGTERM']);assert.throws(()=>new ClaudeCliAdapter({terminationGraceMs:0}),/terminationGraceMs/);});
