import test from 'node:test';import assert from 'node:assert/strict';
import {createNativeHost,createAsyncNativeHost} from '../host.mjs';import {createMultipartFetchTransport} from '../raw-multipart.mjs';
const request=()=>({credential:{headers:{'xi-api-key':'fixture-private'}},url:'https://api.elevenlabs.io/v1/speech-to-text',headers:'{}',fields:[{name:'model_id',value:'fixture-model'}],filename:'audio.webm',mimeType:'audio/webm',bytes:[1,0,255]});
test('generic physical multipart remains inert until explicitly opted in',async()=>{let calls=0;const factory=createMultipartFetchTransport({fetch:async()=>{calls++}});assert.equal((await factory(request())).status,4);assert.equal(calls,0)});
test('generic physical multipart preserves arbitrary bytes and private origin-scoped headers',async()=>{
 const factory=createMultipartFetchTransport({allowRequests:true,allowedOrigins:['https://api.elevenlabs.io'],maxChunkBytes:2,fetch:async(url,init)=>{assert.equal(url,'https://api.elevenlabs.io/v1/speech-to-text');assert.equal(init.redirect,'error');assert.equal(init.headers.get('xi-api-key'),'fixture-private');assert.equal(init.headers.get('content-type'),null);assert.equal(init.body.get('model_id'),'fixture-model');assert.deepEqual([...new Uint8Array(await init.body.get('file').arrayBuffer())],[1,0,255]);return new Response(JSON.stringify({text:'😀'}),{status:200})}});
 const opened=await factory(request());assert.equal(opened.status,1);assert.equal(opened.data,'200');let text='';while(true){const part=await opened.resource.read();if(part.status===2)break;if(part.status===1)text+=part.data;else assert.equal(part.status,3)}assert.deepEqual(JSON.parse(text),{text:'😀'});await opened.resource.close();await factory.dispose();
});
test('multipart rejects header injection, invalid bytes, duplicate fields and invalid origins before fetch',async()=>{
 let calls=0;const factory=createMultipartFetchTransport({allowRequests:true,allowedOrigins:['https://api.elevenlabs.io'],maxUploadBytes:4,fetch:async()=>{calls++}});
 for(const invalid of [{bytes:[256]},{bytes:[]},{bytes:[1,2,3,4,5]},{filename:'../private.webm'},{mimeType:'audio/webm\r\nprivate'},{headers:JSON.stringify({authorization:'wrong'})},{headers:JSON.stringify({'Content-Type':'multipart/form-data'})},{fields:[{name:'x',value:'a'},{name:'x',value:'b'}]},{fields:[{name:'file',value:'x'}]},{url:'https://elsewhere.test/upload'}])assert.equal((await factory({...request(),...invalid})).status,4);
 assert.equal(calls,0);await factory.dispose();
});
test('raw sync and async registries marshal multipart fields without provider semantics',async()=>{
 for(const asyncMode of [false,true]){let sent,closed=0;const factory=req=>{sent=req;return {status:1,data:'200',resource:{close(){closed++;return {status:1,data:''}},read(){return {status:2,data:''}}}}};const host=(asyncMode?createAsyncNativeHost:createNativeHost)({multipart:factory,credentials:new Map([[7,'opaque-private']]),maxUploadBytes:4});const r=request();const open=await host.dispatch('http.multipart_open',[7,r.url,r.headers,r.fields,r.filename,r.mimeType,r.bytes]);assert.equal(open.status,1);assert.equal(sent.credential,'opaque-private');assert.equal(sent.fields[0].name,'model_id');assert.equal(host.openHandles,1);assert.equal((await host.dispatch('http.multipart_open',[7,r.url,r.headers,r.fields,r.filename,r.mimeType,[300]])).status,4);await host.dispatch('transport.close',[open.handle]);assert.equal(closed,1);await host.dispose()}
});
