import {createVoiceRecorder} from './voice-message.mjs';
const safe=(fn,value)=>{try{fn?.(value)}catch{}};
/** Explicit camera attachment capture, separate from call camera context. */
export function createCameraAttachmentCapture({mediaDevices=globalThis.navigator?.mediaDevices,MediaRecorder=globalThis.MediaRecorder,video,canvas,now=()=>performance.now(),maxBytes=8*1024*1024,onState=()=>{},onError=()=>{}}={}){
 let stream,recording,completedVideo,disposed=false,epoch=0,state='off';
 const set=s=>{state=s;safe(onState,s)};
 const stopTracks=s=>{for(const track of s?.getTracks()??[])try{track.stop()}catch{}};
 const recorder=createVoiceRecorder({mediaDevices:{getUserMedia:async()=>{if(!stream)throw Error('Camera is not ready');return stream}},MediaRecorder,now,maxBytes,maxDurationMs:120000,mimeTypes:['video/webm;codecs=vp9','video/webm;codecs=vp8','video/webm','video/mp4'],onError:error=>{set('error');safe(onError,error)},onLimit:result=>{completedVideo=result;stream=undefined;set('recorded')}});
 async function start(){if(disposed)throw Error('Camera capture is disposed');if(state!=='off'&&state!=='error')throw Error('Camera is already active');if(!mediaDevices?.getUserMedia||!video||!canvas)throw Error('Camera capture is unavailable');const token=++epoch;set('requesting');try{const acquired=await mediaDevices.getUserMedia({video:{width:{ideal:640},height:{ideal:480}},audio:false});if(token!==epoch||disposed){stopTracks(acquired);throw Error('Camera capture cancelled')}stream=acquired;video.srcObject=stream;video.muted=true;video.playsInline=true;await video.play();if(token!==epoch||disposed)throw Error('Camera capture cancelled');set('ready')}catch(error){if(token===epoch){stopTracks(stream);stream=undefined;video.srcObject=null;set('error');safe(onError,error)}throw error}}
 async function photo(){if(state!=='ready')throw Error('Camera is not ready');const width=video.videoWidth||640,height=video.videoHeight||480,scale=Math.min(1,640/width,480/height);canvas.width=Math.round(width*scale);canvas.height=Math.round(height*scale);const context=canvas.getContext('2d');if(!context)throw Error('Photo capture is unavailable');context.drawImage(video,0,0,canvas.width,canvas.height);const token=epoch,blob=await new Promise((resolve,reject)=>canvas.toBlob(value=>value?resolve(value):reject(Error('Photo capture failed')),'image/jpeg',0.85));if(token!==epoch||disposed)throw Error('Camera capture cancelled');if(blob.size>maxBytes)throw Error('Photo exceeds attachment size limit');return{blob,mimeType:blob.type,name:'photo.jpg',kind:'photo'}}
 async function startVideo(){if(state!=='ready')throw Error('Camera is not ready');completedVideo=undefined;await recorder.start();recording=true;set('recording')}
 async function finishVideo(){if(!recording)throw Error('No video recording is active');recording=false;const result=completedVideo??await recorder.stop();completedVideo=undefined;stream=undefined;video.srcObject=null;set('off');return{...result,name:result.mimeType.includes('mp4')?'video.mp4':'video.webm',kind:'video'}}
 async function stop(){++epoch;recording=false;await recorder.cancel();stopTracks(stream);stream=undefined;video?.pause?.();if(video)video.srcObject=null;set('off')}
 return{start,photo,startVideo,finishVideo,stop,async dispose(){disposed=true;await stop()},get state(){return state}};
}

/** WhatsApp-shaped controls with explicit recording/capture gestures and text-only submit. */
export function mountComposer(container,{document=container.ownerDocument,onText,onVoiceMessage,onAttachment,onError=()=>{},mediaDevices,MediaRecorder,now}={}){
 let disposed=false,busy=false;const root=document.createElement('div');root.className='dot-composer';const form=document.createElement('form');form.id='message';form.className='dot-composer-row';
 const button=(label,glyph,parent=form)=>{const node=document.createElement('button');node.type='button';node.className='dot-icon-button';node.setAttribute('aria-label',label);node.title=label;node.textContent=glyph;parent.append(node);return node};
 const plus=button('Add attachment','+');plus.setAttribute('aria-expanded','false');const prompt=document.createElement('textarea');prompt.id='prompt';prompt.rows=1;prompt.placeholder='Message';prompt.setAttribute('aria-label','Message');form.append(prompt);const send=button('Send text','↑');send.type='submit';send.hidden=true;const camera=button('Camera attachment','▣'),mic=button('Record voice message','●');
 const status=document.createElement('div');status.className='dot-composer-status';status.setAttribute('aria-live','polite');const cancel=button('Cancel voice recording','Cancel',status);cancel.hidden=true;
 const menu=document.createElement('div');menu.className='dot-attachment-menu';menu.hidden=true;const photos=button('Photos and videos','Photos / library',menu),files=button('Files','Files',menu);
 const input=(accept)=>{const node=document.createElement('input');node.type='file';node.accept=accept;node.hidden=true;root.append(node);return node};const library=input('image/*,video/*'),file=input('');
 const panel=document.createElement('div');panel.className='dot-camera-panel';panel.hidden=true;const video=document.createElement('video'),canvas=document.createElement('canvas');canvas.hidden=true;panel.append(video,canvas);const snap=button('Take photo','Take photo',panel),recordVideo=button('Record silent video attachment','Record silent video',panel),finishVideo=button('Send video attachment','Send video',panel),closeCamera=button('Cancel camera attachment','Cancel',panel);finishVideo.hidden=true;
 root.append(form,status,menu,panel);container.append(root);
 const report=error=>{if(disposed)return;status.dataset.error='true';status.prepend(document.createTextNode(`${error?.message||'Could not complete this action'} `));safe(onError,error)};
 const run=async action=>{if(busy||disposed)return;busy=true;try{await action()}catch(error){report(error)}finally{busy=false}};
 const voice=createVoiceRecorder({mediaDevices,MediaRecorder,now,onState:s=>{mic.setAttribute('aria-label',s==='recording'?'Send voice message':'Record voice message');mic.textContent=s==='recording'?'■':'●';cancel.hidden=!['requesting','recording','stopping'].includes(s);const hasText=!!prompt.value.trim();send.hidden=!hasText;mic.hidden=hasText&&!['requesting','recording','stopping'].includes(s);status.dataset.state=s},onError:report,onLimit:record=>void run(()=>onVoiceMessage?.(record))});
 const capture=createCameraAttachmentCapture({mediaDevices,MediaRecorder,video,canvas,now,onError:report,onState:s=>{panel.dataset.state=s;recordVideo.hidden=s==='recording';finishVideo.hidden=!['recording','recorded'].includes(s);snap.disabled=s!=='ready'}});
 form.onsubmit=event=>{event.preventDefault();const value=prompt.value.trim();if(value)void run(async()=>{await onText?.(value);prompt.value='';prompt.oninput()})};prompt.oninput=()=>{const hasText=!!prompt.value.trim(),recording=['requesting','recording','stopping'].includes(voice.state);send.hidden=!hasText;mic.hidden=hasText&&!recording};prompt.onkeydown=event=>{if(event.key==='Enter'&&!event.shiftKey&&!event.isComposing){event.preventDefault();form.requestSubmit()}};
 plus.onclick=()=>{menu.hidden=!menu.hidden;plus.setAttribute('aria-expanded',String(!menu.hidden))};photos.onclick=()=>library.click();files.onclick=()=>file.click();
 const selected=(node,kind)=>async()=>{const selected=node.files?.[0];node.value='';if(!selected)return;menu.hidden=true;plus.setAttribute('aria-expanded','false');await run(()=>onAttachment?.({file:selected,kind:kind??(selected.type.startsWith('video/')?'video':'photo')}))};library.onchange=selected(library);file.onchange=selected(file,'file');
 mic.onclick=()=>void run(async()=>{if(voice.state==='recording'){const result=await voice.stop();await onVoiceMessage?.(result)}else await voice.start()});cancel.onclick=()=>void voice.cancel();
 camera.onclick=()=>void run(async()=>{panel.hidden=false;await capture.start()});snap.onclick=()=>void run(async()=>{const result=await capture.photo();await onAttachment?.({...result,file:new File([result.blob],result.name,{type:result.mimeType})});await capture.stop();panel.hidden=true});recordVideo.onclick=()=>void run(()=>capture.startVideo());finishVideo.onclick=()=>void run(async()=>{const result=await capture.finishVideo();await onAttachment?.({...result,file:new File([result.blob],result.name,{type:result.mimeType})});panel.hidden=true});closeCamera.onclick=()=>{panel.hidden=true;void capture.stop()};
 return{element:root,prompt,voice,camera:capture,async dispose(){if(disposed)return;disposed=true;await Promise.all([voice.dispose(),capture.dispose()]);root.remove()}};
}
