import type {AssetStore,StoredAsset,SerializedAsset} from './assets.js';
export type {AssetStore,StoredAsset,SerializedAsset} from './assets.js';
export interface MediaAsset {assetId:string;url:string;mimeType:string;name:string;size:number;durationMs?:number}
export interface TimedTranscriptWord {text:string;type:'word'|'spacing'|'audio_event';start:number|null;end:number|null;speakerId:string|null;logprob:number|null}
export interface TranscriptionState {status:'pending'|'running'|'ready'|'failed'|'cancelled';attempt:number;text:string;error:string|null;retryRequired:boolean;provider:'elevenlabs';model:string;sourceAssetId:string;words:TimedTranscriptWord[]}
export interface AudioReplyState {status:'none'|'pending'|'running'|'ready'|'failed'|'cancelled';messageId:string|null;error:string|null}
export type Message={id:string;role:'user'|'assistant';source:'chat'|'call';text:string;status?:'streaming'|'complete'|'failed'|'cancelled'|'fragment';fragments?:{text:string;startMs:number;endMs:number;eventId:string}[];kind?:'audio'|'photo'|'video'|'file';audio?:MediaAsset&{durationMs:number};media?:MediaAsset;transcription?:TranscriptionState;reply?:AudioReplyState;replyTo?:string};
export type AudioMessage=Message&{kind:'audio';audio:MediaAsset&{durationMs:number};transcription:TranscriptionState;reply:AudioReplyState};
export type AttachmentMessage=Message&{kind:'photo'|'video'|'file';media:MediaAsset};
export interface AudioInput {bytes:Uint8Array;mimeType:string;durationMs:number;name?:string}
export interface AttachmentInput {bytes:Uint8Array;mimeType:string;name:string;kind:'photo'|'video'|'file'}
export interface TranscriptionAdapter {readonly model?:string;transcribe(input:{bytes:Uint8Array;mimeType:string;filename?:string},options:{signal:AbortSignal}):Promise<{text:string;words?:{text:string;type:'word'|'spacing'|'audio_event';start?:number|null;end?:number|null;speaker_id?:string|null;logprob?:number}[]}>}
export type Task={id:string;title:string;done:boolean;status:'ready'|'running'|'done'|'failed'|'cancelled';approval:'not-required'|'pending'|'approved'|'rejected';result:string|null;error:string|null};
export interface Snapshot {version:1;id:string;messages:Message[];tasks:Task[];permissions:{microphone:boolean;persistence:boolean};phase:'idle'|'running'|'cancelled'|'failed';inCall:boolean;error:string|null}
export interface Agent {run(request:{prompt:string;messages:{role:string;text:string}[];sessionId:string},options:{signal:AbortSignal}):AsyncIterable<{type:'text_delta'|'result';text:string}>}
export interface PersistedSnapshot extends Snapshot {assets?:SerializedAsset[]}
export interface Persistence {load():PersistedSnapshot|null|Promise<PersistedSnapshot|null>;save(value:PersistedSnapshot):void|Promise<void>;clear():void|Promise<void>}
export class PermissionError extends Error {permission:string}
export function createMemoryPersistence():Persistence;
export interface Assistant {sendAudio(input:AudioInput):Promise<AudioMessage>;sendAttachment(input:AttachmentInput):Promise<AttachmentMessage>;retryTranscription(messageId:string):Promise<AudioMessage>;cancelTranscription(messageId:string):Promise<AudioMessage>;replyToAudio(messageId:string):Promise<AudioMessage>;getAsset(assetId:string):Promise<(StoredAsset&{bytes:Uint8Array})|null>;snapshot():Snapshot;subscribe(listener:(snapshot:Snapshot)=>void):()=>void;setPermission(permission:'microphone'|'persistence',allowed:boolean):Promise<void>;beginCall():void;endCall():void;transcript(text:string):Promise<Snapshot>;recordCallTranscript(role:'user'|'assistant',text:string,options?:{fragment:{startMs:number;endMs:number;eventId:string}}):Promise<Snapshot>;addTask(title:string,options?:{requiresApproval?:boolean}):Promise<Task>;decideTask(id:string,approved:boolean):Promise<void>;runTask(id:string,execute:(task:Task,options:{signal:AbortSignal})=>unknown|Promise<unknown>):Promise<void>;cancelTask(id:string):Promise<void>;runAgentTask(id:string,options:{prompt:string}):Promise<Task>;completeTask(id:string):Promise<void>;send(text:string,options?:{source:'chat'|'call'}):Promise<Snapshot>;cancel():void;restore():Promise<boolean>;clear():Promise<void>}
export function createAssistant(options?:{agent?:Agent;persistence?:Persistence;id?:string;transcriptionAdapter?:TranscriptionAdapter;transcriptionTimeoutMs?:number;assetStore?:AssetStore}):Assistant;
