import lifecycle from './generated/session.mjs';
import attachments from './generated/attachments.mjs';
import {createMemoryAssetStore} from './assets.mjs';
import {MockAgent} from 'near-function/ai/mock';

// Boundary conversion only: Bend owns data reduction, JavaScript owns IO.
const approvals={'not-required':'NoApprovalNeeded',pending:'AwaitingApproval',approved:'ExecutionApproved',rejected:'ExecutionRejected'};
const statuses={ready:'TaskReady',running:'TaskRunning',done:'TaskDone',failed:'TaskFailed',cancelled:'TaskCancelled'};
const messageStatuses={streaming:'StreamingMessage',complete:'CompleteMessage',cancelled:'CancelledMessage',failed:'FailedMessage',fragment:'FragmentMessage'};
const inverse=map=>Object.fromEntries(Object.entries(map).map(([k,v])=>[v,k]));
const approvalNames=inverse(approvals),statusNames=inverse(statuses),messageStatusNames=inverse(messageStatuses);
const nativeMessage=m=>({$:'Message',id:m.id,role:{$:m.role==='user'?'UserMessage':'AssistantMessage'},source:{$:m.source==='call'?'CallMessage':'ChatMessage'},text:m.text,status:{$:messageStatuses[m.status]??'UserRecorded'}});
const nativeTask=t=>({$:'Task',id:t.id,title:t.title,status:{$:statuses[t.status]},approval:{$:approvals[t.approval]},result:t.result??'',error:t.error??''});
const list=values=>values.reduceRight((tail,head)=>({$:'Con',head,tail}),{$:'Nil'});
function appendRecord(values,value,isTask=false,session=lifecycle.initial()){const natives=list(values.map(isTask?nativeTask:nativeMessage));let reduced=isTask?lifecycle.append_task(natives,nativeTask(value)):lifecycle.history_record(session,nativeMessage(value),{$:'Continuity',messages:natives,tasks:{$:'Nil'}}).messages;const originals=new Map(values.map(v=>[v.id,v]));originals.set(value.id,value);const result=[];while(reduced.$==='Con'){result.push(originals.get(reduced.head.id));reduced=reduced.tail}return result}
function reduceMessage(message,event){const next=lifecycle.reduce_text(event,nativeMessage(message));message.text=next.text;const status=messageStatusNames[next.status.$];if(status)message.status=status;return message}
function reduceTask(task,event){const next=lifecycle.reduce_task(event.$==='FinishTask'?{...event,result:event.result??''}:event,nativeTask(task));task.status=statusNames[next.status.$];task.approval=approvalNames[next.approval.$];task.done=task.status==='done';task.error=next.error||null;if(event.$==='FinishTask'&&next.status.$==='TaskDone')task.result=event.result===null?null:next.result;return task}

const assetKinds={audio:'AudioAsset',photo:'PhotoAsset',video:'VideoAsset',file:'FileAsset'};
const transcriptionPhases={pending:'AwaitingTranscription',running:'Transcribing',ready:'Transcribed',failed:'TranscriptionFailed',cancelled:'TranscriptionCancelled'};
const baseMime=value=>typeof value==='string'?value.split(';')[0].trim().toLowerCase():'';
function validMediaMetadata(kind,asset){if(!asset||typeof asset.assetId!=='string'||!/^[A-Za-z0-9][A-Za-z0-9_-]{0,63}$/.test(asset.assetId)||typeof asset.mimeType!=='string'||asset.mimeType.length>160||/[\r\n\0]/.test(asset.mimeType)||typeof asset.name!=='string'||!asset.name.trim()||asset.name.length>128||/[\/\\<>\x00-\x1f\x7f]/.test(asset.name)||!Number.isSafeInteger(asset.size)||asset.size<1||asset.size>8388608)return false;const mime=baseMime(asset.mimeType);if(!/^[a-z0-9][a-z0-9!#$&^_.+-]*\/[a-z0-9][a-z0-9!#$&^_.+-]*$/.test(mime))return false;if(kind==='audio'&&(!mime.startsWith('audio/')||!Number.isSafeInteger(asset.durationMs)||asset.durationMs<0||asset.durationMs>86400000))return false;if(kind==='photo'&&!['image/jpeg','image/png','image/webp','image/gif','image/avif','image/heic','image/heif'].includes(mime))return false;if(kind==='video'&&!['video/mp4','video/webm','video/quicktime','video/ogg'].includes(mime))return false;return !!assetKinds[kind]}
const nativeAsset=(kind,asset)=>({$:'Asset',id:asset.assetId,kind:{$:assetKinds[kind]},mime_type:baseMime(asset.mimeType),name:asset.name,size:asset.size,duration_ms:asset.durationMs??0});
const wordKinds={word:'SpokenWord',spacing:'WordSpacing',audio_event:'AudioEventWord'},wordNames=inverse(wordKinds);
const maybe=value=>value===null||value===undefined?{$:'None'}:{$:'Some',value};
const unmaybe=value=>value.$==='Some'?value.value:null;
function normalizedWords(words=[]){if(!Array.isArray(words)||words.length>40000)throw new TypeError('Invalid transcription words');return words.map(w=>{if(!w||typeof w!=='object')throw new TypeError('Invalid transcription word');const start=w.start??null,end=w.end??null,speakerId=w.speakerId??w.speaker_id??null,logprob=w.logprob??null;if(!w||typeof w.text!=='string'||w.text.length>4000||!wordKinds[w.type]||[start,end,logprob].some(v=>v!==null&&(!Number.isFinite(v)||typeof v!=='number'))||(start!==null&&start<0)||(end!==null&&end<0)||(start!==null&&end!==null&&end<start)||(speakerId!==null&&(typeof speakerId!=='string'||speakerId.length>128)))throw new TypeError('Invalid transcription word');return{text:w.text,type:w.type,start,end,speakerId,logprob}})}
const nativeWords=words=>list(words.map(w=>({$:'TimedWord',text:w.text,kind:{$:wordKinds[w.type]},start:maybe(w.start),end:maybe(w.end),speaker_id:maybe(w.speakerId),logprob:maybe(w.logprob)})));
function publicWords(xs){const values=[];while(xs.$==='Con'){const w=xs.head;values.push({text:w.text,type:wordNames[w.kind.$],start:unmaybe(w.start),end:unmaybe(w.end),speakerId:unmaybe(w.speaker_id),logprob:unmaybe(w.logprob)});xs=xs.tail}return values}
function audioNative(message){const t=message.transcription;return {$:'AudioMessage',message_id:message.id,asset:nativeAsset('audio',message.audio),transcription:{$:'Transcription',phase:{$:transcriptionPhases[t.status]},attempt:t.attempt,provenance:{$:'Provenance',provider:t.provider,model:t.model,source_asset_id:t.sourceAssetId},words:nativeWords(t.words),text:t.text,error:t.error??'',retry_required:t.retryRequired}}}
function projectAudio(message,next){const t=next.transcription;message.transcription={status:attachments.transcription_status(t),attempt:t.attempt,text:t.text,error:t.error||null,retryRequired:t.retry_required,provider:t.provenance.provider,model:t.provenance.model,sourceAssetId:t.provenance.source_asset_id,words:publicWords(t.words)};message.text='';return message}
function applyAudio(message,event){return projectAudio(message,attachments.reduce_audio(event,audioNative(message)))}
const replyPhases={none:'ReplyIdle',pending:'ReplyPending',running:'ReplyRunning',ready:'ReplyReady',failed:'ReplyFailed',cancelled:'ReplyCancelled'};
function applyReply(message,event){const r=message.reply;const next=attachments.reduce_reply(event,{$:'AudioReply',message_id:message.id,response_id:r.messageId??'',phase:{$:replyPhases[r.status]},error:r.error??''});message.reply={status:attachments.reply_status(next),messageId:next.response_id||null,error:next.error||null};return message}
const contextMessages=messages=>messages.filter(m=>!m.kind||(m.kind==='audio'&&m.transcription.status==='ready')).map(m=>({role:m.role,text:m.kind==='audio'?m.transcription.text:m.text})).filter(m=>m.text.trim());
const refs=messages=>[...new Set(messages.filter(m=>m.kind&&assetKinds[m.kind]).map(m=>(m.audio??m.media).assetId))];
function validStoredMessage(m){if(!m||typeof m.id!=='string'||typeof m.text!=='string'||!['chat','call'].includes(m.source)||!['user','assistant'].includes(m.role))return false;if(!m.kind)return !m.audio&&!m.media&&!m.transcription;if(m.role!=='user'||m.source!=='chat')return false;if(m.kind==='audio'){const t=m.transcription,r=m.reply;if(!validMediaMetadata('audio',m.audio)||m.media||!t||!transcriptionPhases[t.status]||!Number.isSafeInteger(t.attempt)||t.attempt<0||t.attempt>3||typeof t.text!=='string'||t.text.length>1048576||(t.error!==null&&typeof t.error!=='string')||typeof t.retryRequired!=='boolean'||m.text!==''||t.provider!=='elevenlabs'||typeof t.model!=='string'||!/^[a-z0-9._-]{1,64}$/i.test(t.model)||t.sourceAssetId!==m.audio.assetId||!r||!replyPhases[r.status]||(r.messageId!==null&&typeof r.messageId!=='string')||(r.error!==null&&typeof r.error!=='string'))return false;try{normalizedWords(t.words)}catch{return false}return t.status==='ready'?!!t.text.trim():t.text===''}return ['photo','video','file'].includes(m.kind)&&validMediaMetadata(m.kind,m.media)&&!m.audio&&!m.transcription}
function persistedAssets(saved){const ids=refs(saved.messages);if(!ids.length){if(saved.assets!==undefined&&(!Array.isArray(saved.assets)||saved.assets.length))throw new Error('Invalid saved assets');return []}if(!Array.isArray(saved.assets)||saved.assets.length!==ids.length)throw new Error('Invalid saved assets');const serialized=new Map(saved.assets.map(a=>[a?.id,a]));if(serialized.size!==ids.length)throw new Error('Invalid saved assets');for(const m of saved.messages){if(!m.kind)continue;const a=m.audio??m.media,r=serialized.get(a.assetId);if(!r||typeof r.bytes!=='string'||r.mimeType!==a.mimeType||r.name!==a.name||r.kind!==m.kind||r.bytes.length/4*3-(r.bytes.endsWith('==')?2:r.bytes.endsWith('=')?1:0)!==a.size)throw new Error('Invalid saved assets')}return saved.assets}

export class PermissionError extends Error { constructor(permission){super(`Permission required: ${permission}`);this.name='PermissionError';this.permission=permission;} }
export function createMemoryPersistence(){let saved=null;return {load:()=>saved&&structuredClone(saved),save:value=>{saved=structuredClone(value)},clear:()=>{saved=null}};}
// Bound the host operation even if an injected adapter ignores its AbortSignal.
async function boundedTranscription(run,control,timeoutMs){
 let timer,onAbort;const aborted=new Promise((_,reject)=>{onAbort=()=>reject(Object.assign(new Error('Transcription cancelled'),{name:'AbortError'}));control.signal.addEventListener('abort',onAbort,{once:true});if(control.signal.aborted)onAbort()});
 const deadline=new Promise((_,reject)=>{timer=setTimeout(()=>{reject(Object.assign(new Error('Transcription timed out'),{transcriptionTimeout:true}));control.abort()},timeoutMs)});
 try{return await Promise.race([Promise.resolve().then(run),aborted,deadline])}finally{clearTimeout(timer);control.signal.removeEventListener('abort',onAbort)}
}
/** One session owns chat, call transcripts and tasks. No storage or external tools are implicit. */
export function createAssistant({agent=new MockAgent(),persistence=null,id='local-session',transcriptionAdapter,transcriptionTimeoutMs=60000,assetStore=createMemoryAssetStore()}={}){
 if(!Number.isSafeInteger(transcriptionTimeoutMs)||transcriptionTimeoutMs<1||transcriptionTimeoutMs>120000)throw new TypeError('Transcription timeout must be 1..120000 milliseconds');
 let state={version:1,id,messages:[],tasks:[],permissions:{microphone:false,persistence:false},lifecycle:lifecycle.initial(),error:null};
 let controller=null, sequence=0, epoch=0, activeRun=0,activeSource=null,agentTaskRunning=false,agentOperationActive=false,activeAudioId=null,clearing=false,restoring=false,transcriptionRunning=0;const transcriptionQueue=[],audioReplyQueue=[];const taskControllers=new Map(),transcriptionControllers=new Map(),assetOperations=new Set(),pendingSaves=new Set();const listeners=new Set();
 const snapshot=()=>structuredClone({...state,phase:lifecycle.phase(state.lifecycle),inCall:lifecycle.in_call(state.lifecycle)});
 const notify=()=>{for(const listener of listeners)listener(snapshot())};
 const transition=name=>{state.lifecycle=lifecycle.update({$:name},state.lifecycle)};
 async function assetOperation(run){const operation=Promise.resolve().then(run);assetOperations.add(operation);try{return await operation}finally{assetOperations.delete(operation)}}
 async function save(){if(!state.permissions.persistence||!persistence)return;const saveEpoch=epoch,data=snapshot();const operation=(async()=>{const assets=await assetStore.export(refs(data.messages));if(saveEpoch!==epoch||!state.permissions.persistence)return;await persistence.save({...data,assets})})();pendingSaves.add(operation);try{await operation}catch(error){if(saveEpoch===epoch){state.error=`Persistence failed: ${String(error?.message??error)}`;notify()}throw error}finally{pendingSaves.delete(operation)}}
 function getAudio(messageId){const message=state.messages.find(m=>m.id===messageId);if(!message||message.kind!=='audio')throw new Error('Unknown audio message');return message}
 function abortTranscriptions(){transcriptionQueue.length=0;audioReplyQueue.length=0;for(const c of transcriptionControllers.values())c.abort();transcriptionControllers.clear()}
 function enqueueTranscription(message){if(transcriptionQueue.length+transcriptionRunning>=32)throw new Error('Audio transcription queue is full');if(transcriptionControllers.has(message.id)||transcriptionQueue.some(e=>e.message===message))throw new Error('Transcription is already queued or running');if(message.transcription.attempt>=3)throw new Error('Transcription retry limit reached');applyAudio(message,{$:'QueueTranscription'});transcriptionQueue.push({message,epoch});notify();pumpTranscriptions()}
 function pumpTranscriptions(){if(transcriptionRunning||clearing||restoring)return;while(transcriptionQueue.length){const entry=transcriptionQueue.shift();if(entry.epoch!==epoch||!state.messages.includes(entry.message)||entry.message.transcription.status==='cancelled')continue;transcriptionRunning++;void transcribe(entry.message).finally(()=>{transcriptionRunning--;pumpTranscriptions()}).catch(()=>{});break}}
 function queueAudioReply(message){if(message.transcription.status!=='ready'||!['none','failed','cancelled'].includes(message.reply.status))return;applyReply(message,{$:'EnqueueReply'});audioReplyQueue.push({message,epoch});notify();pumpAudioReplies()}
 function pumpAudioReplies(){if(controller||agentOperationActive||agentTaskRunning||clearing||restoring)return;while(audioReplyQueue.length){const entry=audioReplyQueue.shift();if(entry.epoch!==epoch||!state.messages.includes(entry.message)||entry.message.transcription.status!=='ready'||entry.message.reply.status!=='pending')continue;void runChat(entry.message.transcription.text,{source:'chat',audioMessage:entry.message}).catch(()=>{});break}}
 async function transcribe(message){const runEpoch=epoch,control=new AbortController();transcriptionControllers.set(message.id,control);applyAudio(message,{$:'BeginTranscription'});const attempt=message.transcription.attempt;notify();const current=()=>runEpoch===epoch&&!control.signal.aborted&&transcriptionControllers.get(message.id)===control&&state.messages.includes(message);
  try{if(!transcriptionAdapter||typeof transcriptionAdapter.transcribe!=='function')throw Object.assign(new Error('Unconfigured'),{unconfigured:true});const result=await boundedTranscription(async()=>{const asset=await assetStore.get(message.audio.assetId);control.signal.throwIfAborted();if(!asset?.bytes)throw new Error('Missing audio asset');return transcriptionAdapter.transcribe({bytes:new Uint8Array(asset.bytes),mimeType:message.audio.mimeType,filename:message.audio.name},{signal:control.signal})},control,transcriptionTimeoutMs);if(!current())return;if(!result||typeof result.text!=='string'||!result.text.trim())throw new Error('Invalid transcription result');if(result.text.length>1048576)throw new Error('Transcription text exceeds bound');applyAudio(message,{$:'TranscriptReceived',attempt,text:result.text,words:nativeWords(normalizedWords(result.words))});queueAudioReply(message);
  }catch(error){if(current()||(error?.transcriptionTimeout&&runEpoch===epoch&&transcriptionControllers.get(message.id)===control&&state.messages.includes(message)))applyAudio(message,{$:'TranscriptFailed',attempt,error:error?.transcriptionTimeout?'ElevenLabs transcription timed out. Retry transcription.':error?.unconfigured?'ElevenLabs transcription is not configured. Configure it on the host, then retry.':'ElevenLabs transcription failed. Retry transcription.'})}
  finally{if(transcriptionControllers.get(message.id)===control)transcriptionControllers.delete(message.id);if(runEpoch===epoch&&state.messages.includes(message)){notify();await save().catch(()=>{})}}
 }
 async function storeMessage(input,kind){if(kind==='audio'&&transcriptionQueue.length+transcriptionRunning>=32)throw new Error('Audio transcription queue is full');if(clearing||restoring)throw new Error('Session is being cleared or restored');if(!(input?.bytes instanceof Uint8Array))throw new TypeError('Attachment bytes must be Uint8Array');if(kind==='audio'&&(typeof input.durationMs!=='number'||!Number.isFinite(input.durationMs)))throw new TypeError('Audio duration must be a finite number');const name=input.name??(kind==='audio'?'recording.'+({ 'audio/webm':'webm','audio/ogg':'ogg','audio/mp4':'m4a','audio/mpeg':'mp3','audio/wav':'wav','audio/x-wav':'wav','audio/flac':'flac','audio/aac':'aac'}[baseMime(input.mimeType)]??'audio'):'attachment');const metadata={assetId:`asset-${++sequence}`,mimeType:input.mimeType,name,size:input.bytes.byteLength,...(kind==='audio'?{durationMs:Math.round(input.durationMs)}:{})};if(!validMediaMetadata(kind,metadata)||!attachments.metadata_valid(nativeAsset(kind,metadata)))throw new TypeError('Invalid attachment metadata or size');const writeEpoch=epoch,originalBytes=new Uint8Array(input.bytes);const stored=await assetOperation(()=>assetStore.put({id:metadata.assetId,bytes:originalBytes,mimeType:metadata.mimeType,name,kind}));if(writeEpoch!==epoch){await assetOperation(()=>assetStore.delete(stored.id));throw new Error('Attachment submission was cleared or restored')}const asset={...metadata,assetId:stored.id,url:stored.url};if(!validMediaMetadata(kind,asset))throw new Error('Invalid stored attachment');const message={id:`message-${++sequence}`,role:'user',source:'chat',kind,text:'',status:'complete',...(kind==='audio'?{audio:asset,transcription:{status:'pending',attempt:0,text:'',error:null,retryRequired:false,provider:'elevenlabs',model:transcriptionAdapter?.model??'scribe_v2',sourceAssetId:asset.assetId,words:[]},reply:{status:'none',messageId:null,error:null}}:{media:asset})};if(kind==='audio')projectAudio(message,attachments.audio_new(message.id,nativeAsset(kind,asset),transcriptionAdapter?.model??'scribe_v2'));else attachments.attachment_new(message.id,nativeAsset(kind,asset));state.messages=appendRecord(state.messages,message,false,state.lifecycle);notify();await save().catch(()=>{});return message}
 function getTask(id){const task=state.tasks.find(t=>t.id===id);if(!task)throw new Error('Unknown task');return task}
 const taskAllowed=task=>lifecycle.task_permitted({$:{'not-required':'NoApprovalNeeded',pending:'AwaitingApproval',approved:'ExecutionApproved',rejected:'ExecutionRejected'}[task.approval]});
 async function runChat(text,{source='chat',audioMessage}={}){
   if(typeof text!=='string'||!text.trim())throw new TypeError('Message text required');if(!['chat','call'].includes(source))throw new TypeError('Unknown message source');if(source==='call'&&!lifecycle.in_call(state.lifecycle))throw new Error('Call is closed');if(controller||agentOperationActive||agentTaskRunning||clearing||restoring)throw new Error('A run is already active');
   const run=++sequence,runEpoch=epoch;agentOperationActive=true;activeAudioId=audioMessage?.id??null;activeRun=run;activeSource=source;controller=new AbortController();const signal=controller.signal;state.error=null;if(!audioMessage)state.messages=appendRecord(state.messages,{id:`message-${++sequence}`,role:'user',source,text:text.trim()},false,state.lifecycle);const response={id:`message-${++sequence}`,role:'assistant',source,text:'',status:'streaming',...(audioMessage?{replyTo:audioMessage.id}:{})};state.messages=appendRecord(state.messages,response,false,state.lifecycle);if(audioMessage)applyReply(audioMessage,{$:'StartReply',response_id:response.id});transition('Start');notify();let terminal=false,finalText='';
   try{for await(const event of agent.run({prompt:text.trim(),messages:contextMessages(state.messages.filter(m=>m!==response)),sessionId:state.id},{signal})){if(activeRun!==run||signal.aborted)break;if(!event||!['text_delta','result'].includes(event.type)||typeof event.text!=='string')throw new TypeError('Invalid agent event');if(terminal)throw new Error('Agent protocol: event after terminal result');if(event.type==='text_delta'){reduceMessage(response,{$:'TextDelta',text:event.text});notify()}else{terminal=true;finalText=event.text}}
    if(signal.aborted||activeRun!==run){reduceMessage(response,{$:'TextCancelled'});if(audioMessage)applyReply(audioMessage,{$:'CancelReply'})}else{if(!terminal)throw new Error('Agent protocol: missing terminal result');reduceMessage(response,{$:'TextResult',text:finalText});if(audioMessage)applyReply(audioMessage,{$:'FinishReply',response_id:response.id});transition('Finish')}
   }catch(error){if(signal.aborted||activeRun!==run){reduceMessage(response,{$:'TextCancelled'});if(audioMessage)applyReply(audioMessage,{$:'CancelReply'})}else{reduceMessage(response,{$:'TextError',message:String(error?.message??error)});state.error=audioMessage?'Audio reply failed.':String(error?.message??error);if(audioMessage)applyReply(audioMessage,{$:'FailReply',response_id:response.id,error:'Audio reply failed.'});transition('RunFailed')}}finally{if(activeRun===run){controller=null;activeRun=0;activeSource=null}agentOperationActive=false;activeAudioId=null;notify();try{if(runEpoch===epoch)await save()}finally{pumpAudioReplies()}}
   return snapshot();
 }
 const api={snapshot,subscribe(listener){listeners.add(listener);listener(snapshot());return()=>listeners.delete(listener)},
  async setPermission(permission,allowed){if(typeof allowed!=='boolean')throw new TypeError('Permission decision must be boolean');if(!['microphone','persistence'].includes(permission))throw new TypeError('Unknown permission');if(permission==='persistence'&&allowed&&!persistence)throw new Error('Supply an explicit persistence adapter first');const p=lifecycle.reduce_permissions({$:({microphone:allowed?'PermitMicrophone':'RevokeMicrophone',persistence:allowed?'PermitPersistence':'RevokePersistence'})[permission]},{$:'Permissions',microphone:{$:state.permissions.microphone?'Granted':'Denied'},persistence:{$:state.permissions.persistence?'Granted':'Denied'}});state.permissions={microphone:lifecycle.permission_granted(p.microphone),persistence:lifecycle.permission_granted(p.persistence)};if(permission==='microphone'){transition(allowed?'GrantMic':'DenyMic');if(!allowed&&activeSource==='call')api.cancel();}notify()},
  beginCall(){if(!state.permissions.microphone)throw new PermissionError('microphone');if(!controller)transition('Finish');transition('BeginCall');notify()},
  endCall(){transition('EndCall');if(activeSource==='call')api.cancel();notify()},
  async recordCallTranscript(role,text,{fragment}={}){if(!state.permissions.microphone)throw new PermissionError('microphone');if(!lifecycle.call_record_permitted(state.lifecycle))throw new Error('Call is closed');if(!['user','assistant'].includes(role)||typeof text!=='string'||!(fragment?text.length:text.trim().length))throw new TypeError('Valid call transcript required');if(fragment&&(!Number.isFinite(fragment.startMs)||!Number.isFinite(fragment.endMs)||fragment.startMs<0||fragment.endMs<fragment.startMs||typeof fragment.eventId!=='string'))throw new TypeError('Valid transcript fragment timing required');const recordEpoch=epoch;const message={id:`message-${++sequence}`,role,source:'call',text:fragment?text:text.trim(),...(fragment?{status:'fragment',fragments:[{...fragment,text}]}:role==='assistant'?{status:'complete'}:{})};state.messages=appendRecord(state.messages,message,false,state.lifecycle);notify();if(recordEpoch===epoch)await save();return snapshot()},
  async sendAudio(asset){const message=await storeMessage(asset,'audio');if(state.messages.includes(message))enqueueTranscription(message);return structuredClone(message)},
  async sendAttachment(asset){if(!['photo','video','file'].includes(asset?.kind))throw new TypeError('Attachment kind required');return structuredClone(await storeMessage(asset,asset.kind))},
  async retryTranscription(messageId){if(clearing||restoring)throw new Error('Session is being cleared or restored');const message=getAudio(messageId);if(transcriptionControllers.has(messageId))throw new Error('Transcription is already pending');if(message.transcription.status==='ready')throw new Error('Audio is already transcribed');enqueueTranscription(message);return structuredClone(message)},
  async cancelTranscription(messageId){const message=getAudio(messageId);for(let i=transcriptionQueue.length-1;i>=0;i--)if(transcriptionQueue[i].message.id===messageId)transcriptionQueue.splice(i,1);transcriptionControllers.get(messageId)?.abort();transcriptionControllers.delete(messageId);applyAudio(message,{$:'CancelTranscription',attempt:message.transcription.attempt});notify();await save();return structuredClone(message)},
  async replyToAudio(messageId){if(clearing||restoring)throw new Error('Session is being cleared or restored');const message=getAudio(messageId);if(message.transcription.status!=='ready')throw new Error('A ready transcript is required');if(['pending','running','ready'].includes(message.reply.status))throw new Error('Audio reply is already queued, running or complete');queueAudioReply(message);return structuredClone(message)},
  async getAsset(assetId){if(!refs(state.messages).includes(assetId))return null;const value=await assetStore.get(assetId);return value?{...value,bytes:new Uint8Array(value.bytes)}:null},
  async transcript(text){if(!lifecycle.in_call(state.lifecycle))throw new Error('Call is closed');return api.send(text,{source:'call'})},
  async addTask(title,{requiresApproval=false}={}){if(typeof title!=='string'||!title.trim())throw new TypeError('Task title required');if(typeof requiresApproval!=='boolean')throw new TypeError('Approval choice must be boolean');const initial=lifecycle.new_task(`task-${++sequence}`,title.trim(),requiresApproval);const task={id:initial.id,title:initial.title,done:false,status:statusNames[initial.status.$],approval:approvalNames[initial.approval.$],result:null,error:null};state.tasks=appendRecord(state.tasks,task,true);notify();await save();return structuredClone(task)},
  async completeTask(id){const task=state.tasks.find(t=>t.id===id);if(!task)throw new Error('Unknown task');if(task.status==='running')throw new Error('Task is running');if(!taskAllowed(task))throw new PermissionError('task approval');reduceTask(task,{$:'FinishTask',result:task.result});notify();await save()},
  async decideTask(id,approved){if(typeof approved!=='boolean')throw new TypeError('Approval decision must be boolean');const task=getTask(id);if(task.approval!=='pending')throw new Error('Task is not awaiting approval');reduceTask(task,{$:approved?'ApproveTask':'RejectTask'});notify();await save()},
  async runTask(id,execute){const task=getTask(id);if(typeof execute!=='function')throw new TypeError('Explicit task executor required');if(!taskAllowed(task))throw new PermissionError('task approval');if(task.status!=='ready')throw new Error('Task is not ready');const taskController=new AbortController();taskControllers.set(id,taskController);reduceTask(task,{$:'StartTask'});notify();
   try{const result=await execute(structuredClone(task),{signal:taskController.signal});if(taskControllers.get(id)!==taskController||taskController.signal.aborted)return;reduceTask(task,{$:'FinishTask',result:result===undefined?null:String(result)})}catch(error){if(!taskController.signal.aborted){reduceTask(task,{$:'FailTask',message:String(error?.message??error)})}}finally{if(taskControllers.get(id)===taskController){taskControllers.delete(id);notify();await save()}}},
  async runAgentTask(id,{prompt}={}){if(typeof prompt!=='string'||!prompt.trim())throw new TypeError('Delegation prompt required');if(controller||agentOperationActive||agentTaskRunning)throw new Error('An agent run is already active');agentTaskRunning=true;try{await api.runTask(id,async(task,{signal})=>{let result=null,terminal=false;for await(const event of agent.run({prompt,messages:contextMessages(state.messages),sessionId:state.id},{signal})){signal.throwIfAborted();if(!event||!['text_delta','result'].includes(event.type)||typeof event.text!=='string')throw new TypeError('Invalid agent event');if(terminal)throw new Error('Agent protocol: event after terminal result');if(event.type==='result'){terminal=true;result=event.text}}if(!terminal)throw new Error('Agent protocol: missing terminal result');return result});return structuredClone(getTask(id))}finally{agentTaskRunning=false;pumpAudioReplies()}},
  async cancelTask(id){const task=getTask(id);const running=taskControllers.get(id);if(task.status==='done')throw new Error('Task is already complete');running?.abort();taskControllers.delete(id);reduceTask(task,{$:'CancelTask'});notify();await save()},
  cancel(){for(const entry of audioReplyQueue)applyReply(entry.message,{$:'CancelReply'});audioReplyQueue.length=0;if(activeAudioId){const audio=state.messages.find(m=>m.id===activeAudioId);if(audio)applyReply(audio,{$:'CancelReply'})}if(controller){controller.abort();activeRun=0;controller=null;activeSource=null;}transition('Cancel');notify()},
  async send(text,options){return runChat(text,options)},
  async restore(){if(!state.permissions.persistence)throw new PermissionError('persistence');const saved=await persistence.load();if(!saved)return false;
   if(saved.version!==1||saved.id!==id||!Array.isArray(saved.messages)||!Array.isArray(saved.tasks)||!saved.messages.every(validStoredMessage)||!saved.tasks.every(t=>t&&typeof t.id==='string'&&typeof t.title==='string'&&typeof t.done==='boolean'&&['ready','running','done','failed','cancelled'].includes(t.status)&&['not-required','pending','approved','rejected'].includes(t.approval)&&(t.result===null||typeof t.result==='string')&&(t.error===null||typeof t.error==='string'))||new Set([...saved.messages,...saved.tasks].map(x=>x.id)).size!==saved.messages.length+saved.tasks.length)throw new Error('Invalid saved session');
   if(controller||agentOperationActive||taskControllers.size||restoring||clearing)throw new Error('Cannot restore during a run');const serialized=persistedAssets(saved);const restoreEpoch=++epoch;restoring=true;abortTranscriptions();try{await assetOperation(()=>assetStore.import(serialized));if(restoreEpoch!==epoch)return false;state.messages=structuredClone(saved.messages);for(const message of state.messages){if(!message.kind)continue;const asset=message.audio??message.media,stored=await assetStore.get(asset.assetId);if(restoreEpoch!==epoch)return false;if(!stored)throw new Error('Missing saved asset');asset.url=stored.url;if(message.kind==='audio'){applyAudio(message,{$:'RestoreTranscription'});applyReply(message,{$:'RestoreReply'})}}state.tasks=structuredClone(saved.tasks).map(t=>reduceTask(t,{$:'RestoreTask'}));sequence=Math.max(sequence,0,...[...state.messages,...state.tasks].map(x=>Number(x.id.split('-').at(-1))||0));state.lifecycle=lifecycle.initial();if(state.permissions.microphone)transition('GrantMic');restoring=false;notify();pumpTranscriptions();return true}finally{restoring=false}},
  async clear(){if(clearing)throw new Error('Session is already being cleared');clearing=true;restoring=false;try{epoch++;abortTranscriptions();api.cancel();for(const c of taskControllers.values())c.abort();taskControllers.clear();state.messages=[];state.tasks=[];state.error=null;state.lifecycle=lifecycle.initial();if(state.permissions.microphone)transition('GrantMic');await Promise.allSettled([...assetOperations,...pendingSaves]);await assetStore.clear();if(state.permissions.persistence)await persistence.clear();clearing=false;notify();pumpTranscriptions();pumpAudioReplies()}finally{clearing=false}}
 };return api;
}
