import {test} from 'node:test';import assert from 'node:assert/strict';import {EventEmitter} from 'node:events';
import {OpenAIRealtimeClient} from '../../ai/src/live.mjs';
import {createAssistant,createMemoryPersistence} from '../src/index.mjs';import {createRealtimeCallBridge} from '../src/live-bridge.mjs';
const tick=()=>new Promise(r=>setImmediate(r));
function setup({assistant=createAssistant(),signal}={}){const socket=new EventEmitter();socket.readyState=1;socket.frames=[];socket.closed=false;socket.send=raw=>socket.frames.push(JSON.parse(raw));socket.close=()=>{socket.closed=true};socket.event=event=>socket.emit('message',JSON.stringify(event));let listener;const browser={events:[],closed:false,send(event){this.events.push(event)},subscribe(fn){listener=fn;return()=>{listener=null}},close(){this.closed=true},command(event){listener?.(event)}};const client=new OpenAIRealtimeClient({apiKey:'fixture',model:'fixture',socketFactory:()=>{setImmediate(()=>socket.event({type:'session.created',session:{id:'native-session'}}));return socket}});const bridge=createRealtimeCallBridge({assistant,client,browser,signal});return {assistant,socket,browser,bridge}}
async function start(f){await f.assistant.setPermission('microphone',true);f.assistant.beginCall();await f.bridge.start()}
test('native audio/transcripts share Dot continuity without another agent request',async()=>{let agentCalls=0;const a=createAssistant({agent:{async *run(){agentCalls++;yield {type:'result',text:'chat reply'}}}});await a.send('previous chat');const f=setup({assistant:a});await start(f);f.browser.command({type:'audio.append',audio:'AA=='});f.browser.command({type:'audio.commit'});assert.deepEqual(f.socket.frames.map(x=>x.type),['session.update','input_audio_buffer.append','input_audio_buffer.commit','response.create']);assert.equal(f.socket.frames[0].session.audio.input.turn_detection,null);f.socket.event({type:'conversation.item.input_audio_transcription.completed',item_id:'input1',transcript:'spoken input'});f.socket.event({type:'response.created',response:{id:'response1'}});f.socket.event({type:'response.output_audio.delta',response_id:'response1',delta:'AA=='});f.socket.event({type:'response.output_audio_transcript.done',response_id:'response1',item_id:'output1',transcript:'spoken reply'});f.socket.event({type:'response.output_audio_transcript.done',response_id:'response1',item_id:'output1',transcript:'spoken reply'});await tick();assert.equal(agentCalls,1);assert.deepEqual(a.snapshot().messages.map(m=>m.source),['chat','chat','call','call']);assert.deepEqual(a.snapshot().messages.slice(-2).map(m=>m.text),['spoken input','spoken reply']);assert.ok(f.browser.events.some(e=>e.type==='audio.delta'&&e.audio==='AA=='));f.bridge.close();await f.bridge.done;assert.equal(f.socket.closed,true);assert.equal(f.browser.closed,true);assert.equal(a.snapshot().inCall,false)});
test('permission denial and direct record guards never connect audio',async()=>{const f=setup();await assert.rejects(f.bridge.start(),/permission/);assert.equal(f.socket.frames.length,0);assert.equal(f.browser.closed,true);await assert.rejects(f.assistant.recordCallTranscript('user','text'),/microphone/);await f.assistant.setPermission('microphone',true);await assert.rejects(f.assistant.recordCallTranscript('user','text'),/Call is closed/)});
test('end call/revoke/cancel/clear closes sockets and ignores late transcripts',async()=>{for(const action of ['endCall','revoke','cancel','clear']){const f=setup();await start(f);if(action==='revoke')await f.assistant.setPermission('microphone',false);else await f.assistant[action]();await f.bridge.done;f.socket.event({type:'conversation.item.input_audio_transcription.completed',item_id:'late',transcript:'late'});await tick();assert.equal(f.assistant.snapshot().messages.length,0);assert.equal(f.socket.closed,true);assert.equal(f.browser.closed,true)}});
test('response cancellation clears output and suppresses late native reply',async()=>{const f=setup();await start(f);f.socket.event({type:'response.created',response:{id:'r'}});await tick();f.browser.command({type:'cancel'});assert.ok(f.socket.frames.some(e=>e.type==='response.cancel'&&e.response_id==='r'));assert.ok(f.socket.frames.some(e=>e.type==='input_audio_buffer.clear'));f.socket.event({type:'response.output_audio.delta',response_id:'r',delta:'AA=='});f.socket.event({type:'response.output_audio_transcript.done',response_id:'r',item_id:'late',transcript:'late'});await tick();assert.equal(f.assistant.snapshot().messages.length,0);assert.ok(!f.browser.events.some(e=>e.type==='audio.delta'));f.bridge.close()});
test('provider failure and external abort clean up and expose error',async()=>{const f=setup();await start(f);f.socket.event({type:'error',error:{code:'fixture_error',message:'fixture failed'}});await f.bridge.done;assert.ok(f.browser.events.some(e=>e.type==='error'&&e.code==='provider_error'));assert.ok(!JSON.stringify(f.browser.events).includes('fixture failed'));assert.equal(f.socket.closed,true);const controller=new AbortController();const g=setup({signal:controller.signal});await start(g);controller.abort();await g.bridge.done;assert.equal(g.browser.closed,true);assert.equal(g.assistant.snapshot().inCall,false)});
test('restoring during native call closes own bridge; transcripts persist opt-in',async()=>{const p=createMemoryPersistence();const a=createAssistant({persistence:p});await a.setPermission('persistence',true);await a.addTask('saved');const f=setup({assistant:a});await start(f);f.socket.event({type:'conversation.item.input_audio_transcription.completed',item_id:'input1',transcript:'saved speech'});await tick();assert.equal(p.load().messages[0].text,'saved speech');await a.restore();await f.bridge.done;assert.equal(f.socket.closed,true);assert.equal(a.snapshot().inCall,false);assert.equal(a.snapshot().messages[0].text,'saved speech')});
test('permission revoked during delayed native connection closes late socket',async()=>{let release;const gate=new Promise(r=>release=r);const a=createAssistant();let nativeClosed=false;const native={configure(){},close(){nativeClosed=true},async *events(){}};const browser={send(){},subscribe(){return()=>{}},close(){}};const bridge=createRealtimeCallBridge({assistant:a,client:{async connect(){await gate;return native}},browser});await a.setPermission('microphone',true);a.beginCall();const pending=bridge.start();await a.setPermission('microphone',false);release();await pending;assert.equal(nativeClosed,true);await bridge.done});
test('cancel before response.created cancels later identity; idle cancel only clears buffer',async()=>{const f=setup();await start(f);f.browser.command({type:'cancel'});assert.ok(!f.socket.frames.some(e=>e.type==='response.cancel'));f.browser.command({type:'audio.commit'});f.browser.command({type:'cancel'});f.socket.event({type:'response.created',response:{id:'late-response'}});f.socket.event({type:'response.output_audio_transcript.done',response_id:'late-response',item_id:'late-output',transcript:'late'});await tick();assert.ok(f.socket.frames.some(e=>e.type==='response.cancel'&&e.response_id==='late-response'));assert.equal(f.assistant.snapshot().messages.length,0);f.bridge.close()});
