import {test} from 'node:test';
import assert from 'node:assert/strict';
import {BrowserVoiceSession, MediaError, mediaCapabilities} from '../src/media.mjs';
import {PCM24kResampler} from '../src/capture-worklet.mjs';
class Socket extends EventTarget {readyState=0;bufferedAmount=0;sent=[];closed=false;send(raw){this.sent.push(JSON.parse(raw));}close(){this.closed=true;this.readyState=3;this.dispatchEvent(new Event('close'));}ready(){this.readyState=1;this.dispatchEvent(new Event('open'));this.frame({type:'status',state:'ready'});}frame(frame){this.dispatchEvent(new MessageEvent('message',{data:typeof frame==='string'?frame:JSON.stringify(frame)}));}}
const node=()=>({connections:[],disconnected:0,connect(other){this.connections.push(other);},disconnect(){this.disconnected++;}});
function fixtures(overrides={}){
 const socket=new Socket();const track={stopped:0,stop(){this.stopped++;}};const stream={getTracks:()=>[track]};const worklet=node();worklet.port={onmessage:null,commands:[],postMessage(message){this.commands.push(message);if(message.type==='flush')this.onmessage?.({data:{type:'flushed',id:message.id}});}};
 const context={currentTime:0,closed:0,resumed:0,modules:[],sources:[],destination:{},audioWorklet:{addModule:async url=>context.modules.push(url)},createMediaStreamSource:()=>node(),createGain:()=>({...node(),gain:{value:1}}),resume:async()=>{context.resumed++;},close:async()=>{context.closed++;},createBuffer:(_channels,count,rate)=>{const data=new Float32Array(count);return{duration:count/rate,rate,data,getChannelData:()=>data};},createBufferSource:()=>{const source={...node(),started:[],stopped:0,start(at){this.started.push(at);},stop(){this.stopped++;}};context.sources.push(source);return source;}};
 const calls=[];const events=[];const options={location:{href:'https://host.test/app'},mediaDevices:{getUserMedia:async constraints=>{calls.push(['permission',constraints]);return stream;}},beforeConnect:async()=>calls.push(['beginCall']),socketFactory:url=>{calls.push(['socket',url]);setImmediate(()=>socket.ready());return socket;},createAudioContext:()=>{calls.push(['context']);return context;},createWorkletNode:()=>worklet,onEvent:event=>events.push(event),...overrides};
 const session=new BrowserVoiceSession(options);return{session,socket,track,stream,worklet,context,calls,events,options};
}
const pcm = values => {const bytes=new Uint8Array(values.length*2);const view=new DataView(bytes.buffer);values.forEach((n,i)=>view.setInt16(i*2,n,true));return bytes;};
const b64=bytes=>btoa(String.fromCharCode(...bytes));
test('media construction never requests permission, creates context or socket',()=>{const f=fixtures();assert.deepEqual(f.calls,[]);assert.equal(f.session.state,'idle');assert.equal(mediaCapabilities.hardwareVerified,false);});
test('explicit start acquires consent then host hook and ready before active capture',async()=>{const f=fixtures();await f.session.start();assert.equal(f.session.state,'active');assert.deepEqual(f.calls.map(c=>c[0]),['permission','beginCall','socket','context']);assert.equal(f.calls[2][1],'wss://host.test/api/audio');assert.equal(f.calls[0][1].video,false);assert.equal(f.context.modules[0],'/api/dot/capture-worklet.mjs');await f.session.stop();assert.equal(f.track.stopped,1);assert.equal(f.context.closed,1);assert.equal(f.socket.closed,true);assert.equal(f.worklet.port.onmessage,null);});
test('host readiness is required after WebSocket open',async()=>{const socket=new Socket();const f=fixtures({socketFactory:()=>socket});const start=f.session.start();await new Promise(r=>setImmediate(r));socket.readyState=1;socket.dispatchEvent(new Event('open'));await new Promise(r=>setImmediate(r));assert.equal(f.session.state,'starting');assert.equal(f.context.resumed,0);socket.frame({type:'status',state:'ready'});await start;await f.session.stop();});
test('capture PCM bytes base64 transfer and flushed commit stay ordered',async()=>{const f=fixtures();await f.session.start();f.worklet.port.onmessage({data:{type:'pcm',bytes:pcm([32767,-32768]).buffer}});f.session.commit();assert.deepEqual(f.socket.sent,[{type:'audio.append',audio:b64(pcm([32767,-32768]))},{type:'audio.commit'}]);assert.equal(f.worklet.port.commands[0].type,'flush');await f.session.stop();});
test('PCM playback is little-endian 24kHz and cancel stops queued audio',async()=>{const f=fixtures();await f.session.start();f.socket.frame({type:'audio.delta',audio:b64(pcm([32767,-32768]))});const playback=f.context.sources[0];assert.equal(playback.buffer.rate,24000);assert.equal(playback.buffer.data[1],-1);assert.ok(playback.buffer.data[0]>.99);f.session.cancel();assert.equal(playback.stopped,1);assert.equal(f.socket.sent.at(-1).type,'response.cancel');f.socket.frame({type:'audio.delta',audio:b64(pcm([1,2]))});assert.equal(f.context.sources.length,1);f.session.commit();f.socket.frame({type:'audio.delta',audio:b64(pcm([1,2]))});assert.equal(f.context.sources.length,2);await f.session.stop();});
test('transcript callbacks are validated and host errors release resources',async()=>{const f=fixtures();await f.session.start();f.socket.frame({type:'transcript',role:'user',text:'fixture transcript'});assert.equal(f.events.at(-1).text,'fixture transcript');f.socket.frame({type:'error',code:'provider_error',message:'private provider body'});await new Promise(r=>setImmediate(r));assert.equal(f.session.state,'failed');assert.equal(f.track.stopped,1);assert.equal(f.context.closed,1);assert.ok(!f.events.at(-1).message.includes('private'));});
test('upload and playback bounds fail closed and release tracks',async()=>{for(const playback of [false,true]){const f=fixtures({maxBufferedBytes:100,maxPlaybackSeconds:0.00001});await f.session.start();if(playback)f.socket.frame({type:'audio.delta',audio:b64(pcm([1,2]))});else{f.socket.bufferedAmount=101;f.worklet.port.onmessage({data:{type:'pcm',bytes:pcm([1,2]).buffer}});}await new Promise(r=>setImmediate(r));assert.equal(f.session.state,'failed');assert.equal(f.track.stopped,1);assert.ok(f.events.some(e=>e.type==='error'&&e.code.endsWith('backpressure')));}});
test('malformed PCM, transcripts and JSON release the active session',async()=>{for(const frame of [{type:'audio.delta',audio:'not-base64'},{type:'audio.delta',audio:b64(Uint8Array.of(1))},{type:'transcript',role:'bad',text:'x'},'invalid']){const f=fixtures();await f.session.start();f.socket.frame(frame);await new Promise(r=>setImmediate(r));assert.equal(f.session.state,'failed');assert.equal(f.track.stopped,1);}});
test('cross-origin socket endpoint rejected without constructing socket and stream released',async()=>{const f=fixtures({endpoint:'wss://foreign.test/audio'});await assert.rejects(f.session.start(),e=>e.code==='cross_origin');assert.ok(!f.calls.some(c=>c[0]==='socket'));assert.equal(f.track.stopped,1);});
test('permission denial does not connect; setup failure cleans acquired native resources',async()=>{const denied=fixtures({mediaDevices:{getUserMedia:async()=>{throw Error('denied');}}});await assert.rejects(denied.session.start(),/denied/);assert.ok(!denied.calls.some(c=>c[0]==='socket'));const failed=fixtures();failed.context.audioWorklet.addModule=async()=>{throw Error('worklet failed');};await assert.rejects(failed.session.start(),/worklet failed/);assert.equal(failed.track.stopped,1);assert.equal(failed.context.closed,1);assert.equal(failed.socket.closed,true);});
test('stop while host readiness pending settles start and releases tracks',async()=>{const socket=new Socket();const f=fixtures({socketFactory:()=>socket});const pending=f.session.start();await new Promise(r=>setImmediate(r));await f.session.stop();await assert.rejects(pending,MediaError);assert.equal(f.track.stopped,1);assert.equal(socket.closed,true);});
test('stop during pending permission releases eventual returned tracks without socket',async()=>{let resolve;const f=fixtures({mediaDevices:{getUserMedia:()=>new Promise(r=>{resolve=r;})}});const pending=f.session.start();await f.session.stop();resolve(f.stream);await assert.rejects(pending,e=>e.code==='stopped');assert.equal(f.track.stopped,1);assert.equal(f.socket.closed,false);});
test('worklet resampling produces mono PCM16 24kHz across processing blocks',()=>{const chunks=[];const converter=new PCM24kResampler(48000,bytes=>chunks.push(bytes));converter.push([new Float32Array(480).fill(1),new Float32Array(480).fill(-1)]);converter.push([new Float32Array(480).fill(1),new Float32Array(480).fill(-1)]);assert.equal(chunks.length,1);assert.equal(chunks[0].length,960);assert.ok(chunks[0].every(value=>value===0));});
test('worklet 44.1kHz conversion clamps and flushes exact complete output samples',()=>{const chunks=[];const converter=new PCM24kResampler(44100,bytes=>chunks.push(bytes));converter.push([new Float32Array(441).fill(2)]);converter.flush();assert.equal(chunks.reduce((n,b)=>n+b.length,0),480);assert.equal(new DataView(chunks[0].buffer).getInt16(0,true),32767);assert.throws(()=>new PCM24kResampler(0,()=>{}),/sample rate/);});

test('host audio.clear interruption stops scheduled playback immediately',async()=>{const f=fixtures();await f.session.start();f.socket.frame({type:'audio.delta',audio:b64(pcm([1,2]))});f.socket.frame({type:'audio.clear'});assert.equal(f.context.sources[0].stopped,1);assert.equal(f.session.state,'active');await f.session.stop();});

test('cancel then recommit ignores stale flush acknowledgements',async()=>{const f=fixtures();await f.session.start();f.worklet.port.postMessage=message=>f.worklet.port.commands.push(message);f.session.commit();const first=f.worklet.port.commands.at(-1).id;f.session.cancel();f.session.commit();const second=f.worklet.port.commands.at(-1).id;assert.notEqual(first,second);f.worklet.port.onmessage({data:{type:'flushed',id:first}});assert.equal(f.socket.sent.filter(e=>e.type==='audio.commit').length,0);f.worklet.port.onmessage({data:{type:'pcm',bytes:pcm([1,2]).buffer}});f.worklet.port.onmessage({data:{type:'flushed',id:second}});assert.deepEqual(f.socket.sent.map(e=>e.type),['response.cancel','audio.append','audio.commit']);await f.session.stop();});
test('stale capture callback from a stopped epoch cannot write into a restarted session',async()=>{const f=fixtures();await f.session.start();const old=f.worklet.port.onmessage;await f.session.stop();await f.session.start();const count=f.socket.sent.length;old({data:{type:'pcm',bytes:pcm([1,2]).buffer}});assert.equal(f.socket.sent.length,count);await f.session.stop();});

test('worklet exported chunk tuning stays bounded',()=>{for(const size of [0,-1,1.5,4801])assert.throws(()=>new PCM24kResampler(48000,()=>{},size),/chunkSamples/);for(const rate of [1e-300,7999,192001,Infinity])assert.throws(()=>new PCM24kResampler(rate,()=>{}),/sample rate/);});

test('camera transport correlates one bounded receipt without changing voice playback lifecycle',async()=>{const f=fixtures();await f.session.start();f.session.cameraEnable();const frame={id:'camera-1',capturedAtMs:Date.now(),dataURI:'data:image/jpeg;base64,/9j/AA=='};const pending=f.session.sendCameraFrame(frame);await assert.rejects(f.session.sendCameraFrame({...frame,id:'camera-2'}),e=>e.code==='camera_pending');f.socket.frame({type:'camera.status',phase:'sent',active:true,id:'camera-other',eventId:'foreign'});f.socket.frame({type:'camera.status',phase:'sent',active:true,id:frame.id,eventId:'image-event-1'});assert.deepEqual(await pending,{status:'sent',id:frame.id,eventId:'image-event-1'});f.socket.frame({type:'camera.status',phase:'accepted',active:true,id:frame.id,eventId:'image-event-1'});assert.equal(f.events.at(-1).phase,'accepted');assert.equal(f.session.state,'active');f.session.cameraDisable();assert.equal(f.socket.sent.at(-1).type,'camera.disable');await f.session.stop()});
test('camera cancellation, host rejection and call stop settle pending frame promises',async()=>{const f=fixtures();await f.session.start();const frame={id:'camera-1',capturedAtMs:Date.now(),dataURI:'data:image/jpeg;base64,/9j/AA=='};const signal=new AbortController();const pending=f.session.sendCameraFrame(frame,{signal:signal.signal});signal.abort();await assert.rejects(pending,e=>e.code==='camera_cancelled');const denied=f.session.sendCameraFrame({...frame,id:'camera-2'});f.socket.frame({type:'camera.status',phase:'error',active:true,id:'camera-2',code:'private-rejected'});await assert.rejects(denied,e=>e.code==='camera_context');assert.equal(f.session.state,'active');const stopped=f.session.sendCameraFrame({...frame,id:'camera-3'});const rejection=assert.rejects(stopped,e=>e.code==='camera_stopped');await f.session.stop();await rejection;assert.equal(f.track.stopped,1);await assert.rejects(f.session.sendCameraFrame(frame),e=>e.code==='not_active')});
test('camera malformed input and status fail closed with bounded metadata',async()=>{const f=fixtures();await f.session.start();for(const frame of [{id:'bad',capturedAtMs:Date.now(),dataURI:'data:image/jpeg;base64,/9j/AA=='},{id:'camera-1',capturedAtMs:Date.now(),dataURI:'https://remote.invalid/image.png'},{id:'camera-1',capturedAtMs:Date.now(),dataURI:'data:image/jpeg;base64,'+'A'.repeat(349561)}])await assert.rejects(f.session.sendCameraFrame(frame),e=>e.code==='camera_frame');f.socket.frame({type:'camera.status',phase:'invented',active:true});await new Promise(r=>setImmediate(r));assert.equal(f.session.state,'failed');assert.equal(f.track.stopped,1)});
