import test from 'node:test';
import assert from 'node:assert/strict';
import {createVoiceRecorder,mountVoiceMessage} from '../src/voice-message.mjs';
import {createCameraAttachmentCapture} from '../src/composer.mjs';
class Recorder {static instances=[];static isTypeSupported=()=>true;constructor(stream,options){this.stream=stream;this.mimeType=options.mimeType;this.state='inactive';Recorder.instances.push(this)}start(){this.state='recording'}stop(){this.state='inactive';this.ondataavailable?.({data:new Blob(['final'],{type:this.mimeType})});this.onstop?.()}}
const device=()=>{const track={stops:0,stop(){this.stops++}},stream={getTracks:()=>[track]};return{track,stream}};
test('voice acquisition is explicit; final chunk and duration survive track teardown',async()=>{const d=device();let acquisitions=0,clock=0;const r=createVoiceRecorder({mediaDevices:{getUserMedia:async c=>{assert.deepEqual(c,{audio:true,video:false});acquisitions++;return d.stream}},MediaRecorder:Recorder,now:()=>clock});assert.equal(acquisitions,0);await r.start();clock=456;const value=await r.stop();assert.equal(await value.blob.text(),'final');assert.equal(value.durationMs,456);assert.equal(d.track.stops,1);assert.equal(r.state,'stopped');await r.dispose()});
test('cancel during permission acquisition stops eventual tracks and prevents recorder start',async()=>{const d=device();let grant;const r=createVoiceRecorder({mediaDevices:{getUserMedia:()=>new Promise(resolve=>grant=resolve)},MediaRecorder:Recorder});const started=r.start();await r.cancel();grant(d.stream);await assert.rejects(started,{code:'cancelled'});assert.equal(d.track.stops,1);assert.equal(r.state,'cancelled')});
test('capture errors and byte overflow release tracks',async()=>{const denied=createVoiceRecorder({mediaDevices:{getUserMedia:async()=>{throw Error('private device details')}},MediaRecorder:Recorder});await assert.rejects(denied.start(),{code:'capture_failed'});const d=device();let failure;const r=createVoiceRecorder({mediaDevices:{getUserMedia:async()=>d.stream},MediaRecorder:Recorder,maxBytes:2,onError:e=>failure=e});await r.start();const rec=Recorder.instances.at(-1);rec.ondataavailable({data:new Blob(['oversize'])});assert.equal(failure.code,'recording_limit');assert.equal(r.state,'failed');assert.equal(d.track.stops,1);await assert.rejects(r.stop(),{code:'not_recording'})});
test('camera photo bounds dimensions and video uses video MIME, always stops hardware',async()=>{const d=device();let acquisitions=0,draw;const video={videoWidth:1920,videoHeight:1080,play:async()=>{},pause(){},srcObject:null};const canvas={getContext:()=>({drawImage:(...args)=>draw=args}),toBlob:fn=>fn(new Blob(['jpeg'],{type:'image/jpeg'}))};const camera=createCameraAttachmentCapture({mediaDevices:{getUserMedia:async c=>{assert.equal(c.audio,false);acquisitions++;return d.stream}},MediaRecorder:Recorder,video,canvas});assert.equal(acquisitions,0);await camera.start();const photo=await camera.photo();assert.equal(photo.kind,'photo');assert.equal(canvas.width,640);assert.equal(canvas.height,360);assert.equal(draw[3],640);await camera.startVideo();const clip=await camera.finishVideo();assert.match(clip.mimeType,/^video\//);assert.equal(clip.kind,'video');assert.equal(d.track.stops,1);await camera.dispose();assert.equal(video.srcObject,null)});
test('camera late permission after cancel is torn down',async()=>{const d=device();let grant;const camera=createCameraAttachmentCapture({mediaDevices:{getUserMedia:()=>new Promise(r=>grant=r)},video:{play:async()=>{},pause(){}},canvas:{}});const pending=camera.start();await camera.stop();grant(d.stream);await assert.rejects(pending,/cancelled/);assert.equal(d.track.stops,1)});
class Element {constructor(tag,doc){this.tagName=tag;this.ownerDocument=doc;this.children=[];this.attributes={};this.open=false}append(...nodes){for(const n of nodes){n.parent=this;this.children.push(n)}}replaceChildren(...nodes){this.children=[];this.append(...nodes)}setAttribute(k,v){this.attributes[k]=v}getAttribute(k){return this.attributes[k]??null}removeAttribute(k){delete this.attributes[k]}set src(v){this.setAttribute('src',v)}get src(){return this.getAttribute('src')}pause(){this.pauses=(this.pauses??0)+1}load(){}remove(){this.parent.children=this.parent.children.filter(x=>x!==this)}}
const doc={createElement(tag){return new Element(tag,this)}};
test('playback stays available on transcript failure; retry and URL teardown use no hardware',async()=>{const container=doc.createElement('div');let created=0,revoked=0,retries=0;const controller=mountVoiceMessage(container,{id:'a',blob:new Blob(['audio']),transcription:{status:'failed'}},{document:doc,URL:{createObjectURL:()=>`blob:${++created}`,revokeObjectURL:()=>revoked++},onRetryTranscription:async id=>{assert.equal(id,'a');retries++;return{id, audio:{url:'/api/assets/a'},transcription:{status:'complete',text:'hello'}}}});const details=controller.element.children[1];assert.equal(details.open,false);assert.equal(controller.audio.src,'blob:1');await details.children[2].children[0].onclick();assert.equal(retries,1);assert.equal(details.children[1].textContent,'hello');assert.equal(controller.audio.src,'/api/assets/a');assert.equal(revoked,1);controller.dispose();assert.equal(container.children.length,0);assert.equal(controller.audio.src,null)});
test('interrupted persisted transcription offers retry, removal releases stale audio',()=>{const container=doc.createElement('div');const view=mountVoiceMessage(container,{id:'a',audio:{url:'/api/assets/a'},transcription:{status:'pending',retryRequired:true}},{onRetryTranscription:()=>{}});assert.equal(view.element.children[1].children[2].children[0].textContent,'Retry transcription');view.update({id:'b',transcription:{status:'complete',text:''}});assert.equal(view.audio.src,null);view.dispose()});
test('media placeholders escape filenames and IDs without trusting asset URLs',async()=>{const {renderAssistant}=await import('../src/browser.mjs');const html=renderAssistant({id:'s',phase:'idle',inCall:false,tasks:[],messages:[{id:'x"<',role:'user',source:'chat',kind:'file',text:'',media:{name:'<img src=x onerror=alert(1)>',url:'javascript:alert(1)'},status:'complete'},{id:'audio-1',role:'user',source:'chat',kind:'audio',text:'',status:'complete'}]});assert.ok(html.includes('File: &lt;img'));assert.ok(!html.includes('<img'));assert.ok(!html.includes('javascript:'));assert.ok(html.includes('data-audio-id="audio-1"'));assert.ok(html.includes('Voice message'))});
test('playback errors have their own accessible alert; native playback and transcript state survive updates',()=>{const container=doc.createElement('div');const view=mountVoiceMessage(container,{id:'a',audio:{url:'/api/assets/a'},transcription:{status:'ready',text:'hello'}});const details=view.element.children[1],alert=view.element.children[2];assert.equal(view.audio.controls,true);assert.equal(view.audio.preload,'metadata');details.open=true;const pauses=view.audio.pauses;view.audio.play=()=>{view.audio.onplaying?.();return Promise.resolve()};view.audio.onerror();assert.equal(alert.getAttribute('role'),'alert');assert.equal(alert.hidden,false);assert.match(alert.textContent,/could not be played/);assert.equal(details.children[1].textContent,'hello');view.update({id:'a',audio:{url:'/api/assets/a'},transcription:{status:'ready',text:'updated'}});assert.equal(details.open,true);assert.equal(view.audio.pauses,pauses);assert.equal(alert.hidden,false);void view.audio.play();assert.equal(alert.hidden,true);view.dispose();assert.equal(view.audio.onerror,null);assert.equal(view.audio.onplaying,null);assert.equal(view.audio.pauses,pauses+1)});
test('maximum duration includes final chunk and releases tracks without a device permission in construction',async()=>{const d=device();let resolveLimit;const limited=new Promise(resolve=>resolveLimit=resolve);let clock=0;const recorder=createVoiceRecorder({mediaDevices:{getUserMedia:async()=>d.stream},MediaRecorder:Recorder,maxDurationMs:15,now:()=>clock,onLimit:resolveLimit});await recorder.start();clock=100;const value=await limited;assert.equal(await value.blob.text(),'final');assert.equal(value.durationMs,15);assert.equal(d.track.stops,1);assert.equal(recorder.state,'stopped');await recorder.dispose()});
test('saved stale data/error callbacks after cancellation cannot mutate a restarted recording',async()=>{const first=device(),second=device();let count=0;const recorder=createVoiceRecorder({mediaDevices:{getUserMedia:async()=>++count===1?first.stream:second.stream},MediaRecorder:Recorder});await recorder.start();const old=Recorder.instances.at(-1),oldData=old.ondataavailable,oldError=old.onerror;await recorder.cancel();await recorder.start();oldData({data:new Blob(['stale'])});oldError();assert.equal(recorder.state,'recording');const value=await recorder.stop();assert.equal(await value.blob.text(),'final');assert.equal(first.track.stops,1);assert.equal(second.track.stops,1);await recorder.dispose()});
test('cancel during asynchronous stop rejects pending capture and ignores final queued data',async()=>{class Delayed extends Recorder {stop(){this.state='inactive'}}const d=device();const recorder=createVoiceRecorder({mediaDevices:{getUserMedia:async()=>d.stream},MediaRecorder:Delayed});await recorder.start();const native=Recorder.instances.at(-1),data=native.ondataavailable,stopped=native.onstop;const pending=recorder.stop();await recorder.cancel();await assert.rejects(pending,{code:'cancelled'});data({data:new Blob(['late-final'])});stopped();assert.equal(recorder.state,'cancelled');assert.equal(d.track.stops,1)});
