import assert from 'node:assert/strict';import {readFileSync,writeFileSync} from 'node:fs';
import {embedNativeMain,createAsyncNativeHost,runNativeIO} from './node_modules/near-function/stdlib/ai/native-host/async.mjs';
import {installNativeHost} from './node_modules/near-function/stdlib/ai/native-host/host.mjs';
import {createMultipartFetchTransport} from './node_modules/near-function/stdlib/ai/native-host/raw-multipart.mjs';
writeFileSync('transcription-program.mjs',embedNativeMain(readFileSync('transcription-program.js','utf8')));const {default:main}=await import('./transcription-program.mjs');
const kind=value=>value.$.split('.').at(-1);const rows=list=>{const result=[];while(list.$==='Con'){result.push(list.head);list=list.tail}assert.equal(list.$,'Nil');return result};
globalThis.fetch=()=>{throw Error('Provider network forbidden in packed native transcription fixture')};
const transcript={text:'Installed transcript 😀',language_code:'eng',language_probability:0.98,words:[{text:'Installed',type:'word',start:0,end:0.5,logprob:-0.1,speaker_id:'speaker_0'}],transcription_id:'packed-fixture',audio_duration_secs:1};
for(const mode of ['success','fragmented','http_error','invalid_json','truncated_json']){
 let fetched=0,closed=0,reads=0;const wire=mode==='invalid_json'?'{broken':mode==='truncated_json'?JSON.stringify(transcript).slice(0,-1):JSON.stringify(transcript);
 const physical=createMultipartFetchTransport({allowRequests:true,allowedOrigins:['https://api.elevenlabs.io'],maxChunkBytes:mode==='fragmented'?17:65536,fetch:async(url,options)=>{fetched++;assert.equal(url,'https://api.elevenlabs.io/v1/speech-to-text');assert.equal(options.redirect,'error');assert.equal(options.headers.get('xi-api-key'),'offline-transcription-private');assert.equal(options.headers.get('content-type'),null);assert.equal(options.body.get('model_id'),'scribe_v2');assert.equal(options.body.get('timestamps_granularity'),'word');assert.equal(options.body.get('diarize'),'false');const file=options.body.get('file');assert.equal(file.name,'voice.webm');assert.equal(file.type,'audio/webm');assert.deepEqual([...new Uint8Array(await file.arrayBuffer())],[1,0,255]);return new Response(new ReadableStream({start(controller){const bytes=new TextEncoder().encode(wire);controller.enqueue(bytes.subarray(0,10));controller.enqueue(bytes.subarray(10));controller.close()}}),{status:mode==='http_error'?401:200})}});
 const multipart=async request=>{const reply=await physical(request);assert.ok(reply.resource);const close=reply.resource.close.bind(reply.resource),read=reply.resource.read.bind(reply.resource);reply.resource.close=async()=>{closed++;return close()};reply.resource.read=async()=>{reads++;return read()};return reply};
 const host=createAsyncNativeHost({credentials:new Map([[7,{headers:{'xi-api-key':'offline-transcription-private'}}]]),multipart});const remove=installNativeHost(host);
 try{const receipt=await runNativeIO(main(),{timeoutMs:10000,dispose:async()=>{await host.dispose();await physical.dispose()}});assert.equal(fetched,1);assert.equal(closed,1);assert.equal(host.openHandles,0);if(mode==='success'||mode==='fragmented'){assert.equal(kind(receipt.event),'Completed');assert.equal(receipt.event.transcript.text,transcript.text);assert.equal(rows(receipt.event.transcript.words)[0].text,'Installed');assert.ok(Math.abs(receipt.event.transcript.language_probability-0.98)<0.00001)}else{assert.equal(kind(receipt.event),'FailedEvent');if(mode==='http_error'){assert.equal(receipt.event.error.status,401);assert.equal(reads,0)}}}finally{remove()}
}
console.log('Actual packed native Scribe typed upload → generic FormData/physical fake fetch → raw response chunks → Bend typed transcript decode/EOF/HTTP guard/scoped close passed; no provider connection or real transcription.');
