import assert from 'node:assert/strict';import Voice from './voice.mjs';
const kind=value=>value.$.split('.').at(-1),done=result=>{assert.equal(result.$,'Done',result.error);return result.value};
let rt=Voice.rt_initial();const prefix=rt.$.slice(0,rt.$.lastIndexOf('.'));
const ctor=(name,fields={})=>({$:prefix+'.'+name,...fields});
const rtEvent=value=>done(Voice.rt_decode(JSON.stringify(value)));
rt=Voice.rt_reduce(rtEvent({type:'session.created',session:{id:'session-fixture'}}),rt);assert.equal(kind(rt.phase),'Ready');
assert.equal(Voice.rt_prepare(ctor('AppendAudio',{pcm16_base64:'AQ=='}),rt).$,'Fail');
rt=Voice.rt_reduce(rtEvent({type:'response.created',response:{id:'response-fixture'}}),rt);
const unowned=Voice.rt_reduce(rtEvent({type:'response.output_audio.delta',response_id:'foreign-response',delta:'AAA='}),rt);assert.equal(kind(unowned.phase),'Broken');
rt=Voice.rt_reduce(rtEvent({type:'response.output_audio.delta',response_id:'response-fixture',delta:'AAA='}),rt);assert.equal(kind(rt.phase),'Ready');
const terminal=rtEvent({type:'response.done',response:{id:'response-fixture',status:'completed',usage:{input_tokens:3,output_tokens:2}}});assert.equal(kind(terminal.usage),'ReportedTokens');assert.equal(terminal.usage.input_tokens,3);
rt=Voice.rt_reduce(terminal,rt);assert.equal(rt.active_responses.$,'Nil');assert.equal(Voice.rt_prepare(ctor('CancelResponse',{response_id:'response-fixture'}),rt).$,'Fail');
let live=Voice.live_initial();const liveEvent=value=>done(Voice.live_decode(JSON.stringify(value)));
live=Voice.live_reduce(liveEvent({type:'session.started',session:{id:'live-fixture'}}),live);
live=Voice.live_reduce(liveEvent({type:'session.delegation.created',delegation:{id:'delegation-fixture',target:'client'},offset_ms:5}),live);
const command=ctor('AppendContext',{event_id:'context-fixture',delegation_id:{$:'Some',value:'delegation-fixture'},kind:ctor('Commentary'),content:'Literal $(never-run) context'});
const wire=JSON.parse(Voice.live_encode(command));assert.equal(wire.type,'session.commentary.append');assert.equal(wire.delegation_id,'delegation-fixture');
live=done(Voice.live_prepare(command,live));assert.equal(live.pending.$,'Con');assert.equal(Voice.live_prepare(command,live).$,'Fail');
const wrong=Voice.live_reduce(liveEvent({type:'session.thinking.appended',client_event_id:'context-fixture'}),live);assert.equal(kind(wrong.phase),'Broken');
live=Voice.live_reduce(liveEvent({type:'session.commentary.appended',client_event_id:'context-fixture'}),live);assert.equal(live.pending.$,'Nil');
live=Voice.live_reduce(liveEvent({type:'session.usage.updated',usage:{seconds:1.25}}),live);assert.equal(live.usage_seconds,1.25);
const aborted=Voice.live_abort(live);assert.equal(aborted.finalized,false);assert.equal(kind(aborted.phase),'Broken');
live=Voice.live_reduce(liveEvent({type:'session.closed',session:{id:'live-fixture'},reason:'closed',usage:{seconds:2.5}}),live);assert.equal(live.finalized,true);assert.equal(kind(live.phase),'Closed');assert.equal(live.usage_seconds,2.5);
assert.equal(Voice.live_decode(JSON.stringify({type:'session.delegation.created',delegation:{id:'x',target:'client'},offset_ms:4294967296})).$,'Fail');
console.log('Installed native voice dynamic JS-injected fixtures pass: Realtime ownership/PCM/usage, GPT-Live delegation/ack correlation/usage/abort/final close; no compile-time constant JSON normalization.');
